---
sidebar: sidebar 
permalink: modern-apps/fpd-ai-dl-deploy.html 
keywords: flexpod, cisco, ai, ml, ucs, deep, learning, deploy, data, center 
summary: 'Questo documento fornisce dettagli sull"implementazione e indicazioni sull"integrazione della piattaforma Cisco UCS C480 ML M5 nella soluzione per data center FlexPod per offrire un approccio unificato per fornire funzionalità ai e ML all"interno dell"infrastruttura convergente.' 
---
= Data center FlexPod per l'ai e L'ML combinati con Cisco UCS 480 ML per l'apprendimento approfondito - implementazione
:allow-uri-read: 


Haseeb Niazi, Cisco Arvind Ramakrishnan, NetApp

[role="lead"]
Questo documento fornisce dettagli sull'implementazione e indicazioni sull'integrazione della piattaforma Cisco UCS C480 ML M5 nella soluzione per data center FlexPod per offrire un approccio unificato per fornire funzionalità ai e ML all'interno dell'infrastruttura convergente. Questo documento spiega anche la configurazione delle GPU NVIDIA sulle piattaforme Cisco UCS C220 e C240. Per una discussione dettagliata sulla progettazione delle piattaforme e delle tecnologie utilizzate in questa soluzione, fare riferimento a. link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_c480m5l_aiml_design.html["Data center FlexPod per l'ai e L'ML combinati con Cisco UCS 480 ML per un design di deep learning"^].

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_480ml_aiml_deployment.html["Data center FlexPod per l'ai e L'ML combinati con Cisco UCS 480 ML per l'apprendimento approfondito - implementazione"^]
