---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_deployment_procedures_overview.html 
keywords: configure,  express, flexpod, cisco, series, c190, deployment, overview 
summary: Questo documento fornisce informazioni dettagliate sulla configurazione di un sistema FlexPod Express completamente ridondante e ad alta disponibilità. Per riflettere questa ridondanza, i componenti configurati in ogni fase sono indicati come componente A o componente B. 
---
= Panoramica
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Questo documento fornisce informazioni dettagliate sulla configurazione di un sistema FlexPod Express completamente ridondante e ad alta disponibilità. Per riflettere questa ridondanza, i componenti configurati in ogni fase sono indicati come componente A o componente B. Ad esempio, i controller A e B identificano i due storage controller NetApp forniti in questo documento. Gli switch A e B identificano una coppia di switch Cisco Nexus.

Inoltre, questo documento descrive i passaggi per il provisioning di più host Cisco UCS, identificati in sequenza come server A, server B e così via.

Per indicare che è necessario includere in una fase le informazioni relative all'ambiente in uso, `\<<text>>` viene visualizzato come parte della struttura dei comandi. Vedere l'esempio seguente per `vlan create` comando:

....
Controller01> network port vlan create –node <<var_nodeA>> -vlan-name <<var_vlan-name>>
....
Questo documento consente di configurare completamente l'ambiente FlexPod Express. In questo processo, diversi passaggi richiedono l'inserimento di convenzioni di denominazione specifiche del cliente, indirizzi IP e schemi VLAN (Virtual Local Area Network). La seguente tabella descrive le VLAN richieste per l'implementazione, come descritto in questa guida. Questa tabella può essere completata in base alle variabili specifiche del sito e utilizzata per implementare le fasi di configurazione del documento.


NOTE: Se si utilizzano VLAN di gestione separate in-band e out-of-band, è necessario creare un percorso Layer-3 tra di esse. Per questa convalida, è stata utilizzata una VLAN di gestione comune.

|===
| Nome VLAN | Scopo della VLAN | ID VLAN |  


| VLAN di gestione | VLAN per le interfacce di gestione | 3437 | VSwitch0 


| VLAN NFS | VLAN per traffico NFS | 3438 | VSwitch0 


| VLAN VMware vMotion | VLAN designata per lo spostamento delle macchine virtuali (VM) da un host fisico all'altro | 3441 | VSwitch0 


| VLAN del traffico delle macchine virtuali | VLAN per il traffico delle applicazioni VM | 3442 | VSwitch0 


| ISCSI-A-VLAN | VLAN per il traffico iSCSI sul fabric A. | 3439 | IScsiBootvSwitch 


| ISCSI-B-VLAN | VLAN per il traffico iSCSI sul fabric B. | 3440 | IScsiBootvSwitch 


| VLAN nativa | VLAN a cui sono assegnati frame senza tag | 2 |  
|===
I numeri VLAN sono necessari per tutta la configurazione di FlexPod Express. Le VLAN sono indicate come `\<<var_xxxx_vlan>>`, dove `xxxx` È lo scopo della VLAN (ad esempio iSCSI-A).

In questa convalida sono stati creati due vSwitch.

La seguente tabella elenca i vSwitch della soluzione.

|===
| Nome vSwitch | Adattatori attivi | Porte | MTU | Bilanciamento del carico 


| VSwitch0 | Vmnic2, vmnic4 | predefinito (120) | 9000 | Routing basato su hash IP 


| IScsiBootvSwitch | Vmnic3, vmnic5 | predefinito (120) | 9000 | Routing basato sull'ID della porta virtuale di origine. 
|===

NOTE: Il metodo hash IP per il bilanciamento del carico richiede una configurazione appropriata per lo switch fisico sottostante utilizzando SRC-DST-IP EtherChannel con un canale porta statico (mode on). In caso di connettività intermittente a causa di una possibile errata configurazione dello switch, chiudere temporaneamente una delle due porte uplink associate sullo switch Cisco per ripristinare la comunicazione con la porta vmkernel di gestione ESXi, durante la risoluzione dei problemi relativi alle impostazioni del canale porta.

La tabella seguente elenca le macchine virtuali VMware create.

|===
| Descrizione della macchina virtuale | Nome host 


| VMware vCenter Server | FlexPod-VCSA 


| Virtual Storage Console | FlexPod-VSC 
|===