---
sidebar: sidebar 
permalink: express/express-c-series-aff220-design_solution_verification.html 
keywords: verification, express 
summary: 'Dalla ridondanza e disponibilità a ogni singola funzionalità, l"intera architettura FlexPod Express viene validata per infondere fiducia nei nostri clienti e per creare fiducia nel processo di progettazione.' 
---
= Verifica della soluzione
:allow-uri-read: 


[role="lead"]
Cisco e NetApp hanno progettato e costruito FlexPod Express per fungere da piattaforma infrastrutturale di prim'ordine per i propri clienti. Poiché è stato progettato con componenti leader del settore, i clienti possono affidarsi a FlexPod Express come base dell'infrastruttura. In linea con i principi fondamentali del portfolio FlexPod, l'architettura FlexPod Express è stata testata a fondo dagli architetti e dagli ingegneri dei data center Cisco e NetApp. Dalla ridondanza e disponibilità a ogni singola funzionalità, l'intera architettura FlexPod Express viene validata per infondere fiducia nei nostri clienti e per creare fiducia nel processo di progettazione.

VMware vSphere 6.7 è stato verificato sui componenti dell'infrastruttura FlexPod Express. Questa convalida includeva opzioni di connettività uplink 10 GbE per l'hypervisor.

link:express-c-series-aff220-design_conclusion.html["Prossimo: Conclusione."]
