---
sidebar: sidebar 
permalink: express/express-nva-1154-deploy.html 
keywords: flexpod, cisco, express, vmware, vsphere, ucs, aff, fas, deployment, nva 
summary: La soluzione FlexPod Express per VMware vSphere 7.0 con Cisco UCS Mini e NetApp AFF/FAS sfrutta Cisco UCS Mini con server blade B200 M5, Cisco UCS 6324 in-chassis Fabric Interconnect, switch Cisco Nexus 31108PC-V o altri switch compatibili. 
---
= FlexPod Express per VMware vSphere 7.0 con Cisco UCS Mini e NetApp AFF/FAS - NVA - implementazione
:allow-uri-read: 


Jyh-ishing Chen, NetApp

[role="lead"]
La soluzione FlexPod Express per VMware vSphere 7.0 con Cisco UCS Mini e NetApp AFF/FAS sfrutta Cisco UCS Mini con server blade B200 M5, Cisco UCS 6324 in-chassis Fabric Interconnect, switch Cisco Nexus 31108PC-V o altri switch compatibili e la coppia di controller ha NetApp AFF A220, C190 o FAS2700, Che esegue il software di gestione dei dati NetApp ONTAP 9.7. Questo documento sull'implementazione dell'architettura verificata di NetApp fornisce le procedure dettagliate necessarie per configurare i componenti dell'infrastruttura e per implementare VMware vSphere 7.0 e i relativi strumenti per creare un'infrastruttura virtuale basata su FlexPod Express altamente affidabile e ad alta disponibilità.

link:https://www.netapp.com/pdf.html?item=/media/21938-nva-1154-DEPLOY.pdf["FlexPod Express per VMware vSphere 7.0 con Cisco UCS Mini e NetApp AFF/FAS - NVA - implementazione"^]
