---
sidebar: sidebar 
permalink: express/express-c-series-aff220-deploy_netapp_aff_storage_deployment_procedure_@part_2@.html 
keywords: san, map, boot, storage, setup, aff, deployment, procedure, igroups 
summary: Per creare igroups, è necessario disporre degli IQN iSCSI Initiator e completare i seguenti passaggi. 
---
= Procedura di implementazione dello storage NetApp AFF (parte 2)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Configurazione dello storage di boot SAN ONTAP



=== Creare igroups iSCSI

Per creare igroups, completare il seguente passaggio:

Per questa fase, sono necessari gli IQN iSCSI Initiator della configurazione del server.

. Dalla connessione SSH del nodo di gestione del cluster, eseguire i seguenti comandi. Per visualizzare i tre igroups creati in questa fase, eseguire il comando igroup show.
+
....
igroup create –vserver Infra-SVM –igroup VM-Host-Infra-A –protocol iscsi –ostype vmware –initiator <<var_vm_host_infra_a_iSCSI-A_vNIC_IQN>>, <<var_vm_host_infra_a_iSCSI-B_vNIC_IQN>>
igroup create –vserver Infra-SVM –igroup VM-Host-Infra-B –protocol iscsi –ostype vmware –initiator <<var_vm_host_infra_b_iSCSI-A_vNIC_IQN>>, <<var_vm_host_infra_b_iSCSI-B_vNIC_IQN>>
....
+

NOTE: Questa fase deve essere completata quando si aggiungono altri server Cisco UCS C- Series.





== Mappare le LUN di avvio a igroups

Per mappare le LUN di avvio a igroups, eseguire i seguenti comandi dalla connessione SSH di gestione del cluster:

....
lun map –vserver Infra-SVM –volume esxi_boot –lun VM-Host-Infra- A –igroup VM-Host-Infra- A –lun-id 0
lun map –vserver Infra-SVM –volume esxi_boot –lun VM-Host-Infra- B –igroup VM-Host-Infra- B –lun-id 0
....

NOTE: Questa fase deve essere completata quando si aggiungono altri server Cisco UCS C-Series.

link:express-c-series-aff220-deploy_vmware_vsphere_6.7_deployment_procedure.html["Procedura di implementazione di VMware vSphere 6.7."]
