---
settings:
  name: FlexPod
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione sulle soluzioni FlexPod
    url: "/index.html"
  - section: fp-def
  - section: flexpod-dc
  - section: hybrid-cloud
  - section: ent-db
  - section: healthcare
  - section: vdi
  - section: modern-apps
  - section: express
  - section: security
  - section: ontap-connector-for-intersight
  - section: infrastructure
  - title: Note legali
    url: "/legal-notices.html"
