---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_cisco_components.html 
keywords: cisco, components, ucs, fabric, interconnect, server, rack, apic, nexus, software, support, mds, x-series-modular, x-series-direct 
summary: 'Cisco ha contribuito in modo sostanziale alla progettazione e all"architettura di FlexPod, coprendo sia il livello di elaborazione che quello di rete della soluzione. Questa sezione descrive le opzioni Cisco UCS e Cisco Nexus disponibili per FlexPod.' 
---
= Componenti Cisco
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cisco ha contribuito in modo sostanziale alla progettazione e all'architettura di FlexPod, coprendo sia il livello di elaborazione che quello di rete della soluzione. Questa sezione descrive le opzioni Cisco UCS, Nexus e MDS disponibili per FlexPod.



[[cisco-ucs-fabric-interconnect-options]]
== Opzioni di interconnessione fabric Cisco UCS

L'architettura FlexPod richiede interconnessioni fabric ridondanti. Quando si aggiungono più chassis Cisco UCS a una coppia di interconnessioni fabric, tenere presente che il numero massimo di chassis in un ambiente è determinato sia da un limite di architettura che da un limite di porta.

I codici articolo riportati nella tabella seguente si riferiscono ai base fabric interconnects. Non includono l'alimentatore (PSU) né i moduli SFP+, QSFP+ o di espansione.

|===
| Cisco UCS Fabric Interconnect | Codice del ricambio | Specifiche tecniche 


| Cisco UCS 6664 | UCS-FI-6664-U .2+| https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-6600-series-fabric-interconnect-specsheet.pdf["Cisco UCS 6600 Series Fabric Interconnect"] 


| Cisco UCS 6652 | UCS-FI-6652-U 


| Cisco UCS 6536 | UCSX-FI-6536-U | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-6536-fabric-interconnect-spec-sheet.pdf["Cisco UCS 6536 Fabric Interconnect"] 


| Cisco UCS 6454 | UCS-FI-6454-U. .2+| https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/6400-specsheet.pdf["Cisco UCS 6400 Series Fabric Interconnect"] 


| Cisco UCS 64108 | UCS-FI-64108-U 


| UCS 9108 100G Fabric Interconnect (Cisco UCS X-Series Direct) | UCSX-S9108-100G | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf["Cisco UCS 9108 Fabric Interconnect"] 
|===


[[cisco-ucs-x-series-chassis-option]]
== Opzione chassis Cisco UCS X-Series

Per utilizzare i nodi di calcolo Cisco UCS X-Series, è necessario disporre di uno chassis Cisco UCS X-Series. La seguente tabella descrive l'opzione chassis di Cisco UCS X-Series.

|===
| Blade Cisco UCS X-Series | Codice del ricambio | Specifiche tecniche 


| Chassis Cisco UCS X9508 | UCSX-9508 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html?ccid=cc002456&oid=dstcsm026317["Chassis Cisco UCS X9508"] 
|===
Ogni chassis Cisco UCS 9508 deve disporre di due Cisco UCS 9108 Intelligent Fabric Modules (IFM) per fornire una connettività ridondante alle interconnessioni fabric.



[[cisco-ucs-x-series-device-options]]
== Opzioni dei dispositivi Cisco UCS X-Series

I nodi di calcolo Cisco UCS X-Series sono disponibili con diverse opzioni di CPU, memoria e i/O. I numeri di parte elencati nella tabella seguente si riferiscono al nodo di base. Non includono la CPU, la memoria, i dischi o le schede mezzanine. Sono disponibili diverse opzioni di configurazione supportate nell'architettura FlexPod.

|===
| Nodi di calcolo Cisco UCS X-Series | Codice del ricambio | Specifiche tecniche 


| Cisco UCS X210c M7 | UCSX-210C-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html["Nodo di calcolo Cisco UCS X210c M7"] 


| Cisco UCS X210c M8 | UCSX-210C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html["Nodo di calcolo Cisco UCS X210c M8"] 


| Cisco UCS X215c M8 | UCSX-215C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html["Nodo di calcolo Cisco UCS X215c M8"] 


| Cisco UCS X410c M7 | UCSX-410C-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html["Nodo di calcolo Cisco UCS X410c M7"] 


| Cisco UCS X410c M8 | UCSX-410C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html["Nodo di calcolo Cisco UCS X410c M8"] 
|===
La tabella seguente elenca i nodi PCI Express disponibili per il chassis Cisco UCS X-Series.

|===
| Nodi PCIe Cisco UCS X-Series | Codice del ricambio | Specifiche tecniche 


| Cisco UCS X580p PCIe Node | UCSX-580P-U | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x580p-pcie-node-ds.html["Cisco UCS X580p PCIe Node"] 


| Cisco UCS X440p PCIe Node | UCSX-440P | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x440p-pcle-node-ds.html["Cisco UCS X440p PCIe Node"] 
|===
La tabella seguente elenca i moduli X-Fabric disponibili per il chassis Cisco UCS X-Series.

|===
| Cisco UCS X-Series X-Fabric Modules | Codice del ricambio | Specifiche tecniche 


| Modulo Cisco UCS 9108 Intelligent Fabric | UCSX-I-9108-100G | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-9108-100g-intelligent-fabric-module-spec-sheet.pdf["Modulo Cisco UCS 9108 Intelligent Fabric"] 


| Modulo Cisco UCS X9516 X-Fabric | UCSX-FS-9516 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-9516-x-fabric-module-ds.html["Modulo Cisco UCS X9516 X-Fabric"] 


| Modulo Cisco UCS X9416 X-Fabric | UCSX-F-9416 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/solution-overview-c22-2432175.html?ccid=cc002456&oid=sowcsm025665["Modulo Cisco UCS X9416 X-Fabric"] 
|===


[[cisco-ucs-x-series-modular-system]]
== Cisco UCS X-Series Modular System

Il sistema modulare Cisco UCS X-Series inizia con il chassis server Cisco UCS X9508, progettato per essere adattabile e pronto al futuro. Il chassis ha un fabric Ethernet unificato con Cisco UCS Intelligent Fabric Modules e Cisco UCS X-Fabric Technology per altre tecnologie. Nella parte superiore posteriore del chassis ci sono due Intelligent Fabric Modules che collegano il chassis agli upstream Cisco UCS 6400, 6500 e UCS 6600 Series Fabric Interconnects.

Per una rapida panoramica delle funzionalità e delle caratteristiche di Cisco UCS X-Series, vedi link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-modular-system-aag.html["Cisco UCS X-Series Modular System: panoramica"^].

I nodi di calcolo Cisco UCS X215c M8, Cisco UCS X210c e Cisco UCS X410c offrono le funzionalità sia dei server blade che dei server rack, offrendo densità di calcolo, capacità di storage ed espandibilità in un unico form factor.

Il nodo PCIe Cisco UCS X440p supporta l'aggiunta di GPU con PCIe Gen 4.0 tramite il modulo Cisco UCS X9416 X-Fabric. Il nodo PCIe Cisco UCS X580p supporta l'aggiunta di GPU con PCIe Gen 5.0 tramite il modulo Cisco UCS X9516 X-Fabric.

Per ulteriori informazioni sui componenti della soluzione Cisco UCS X-Series Modular System, consulta le specifiche tecniche di ciascuno di questi componenti nelle sezioni precedenti.


NOTE: Consulta il seguente link per le specifiche tecniche complete del sistema modulare Cisco UCS X-Series: link:https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-x-series-modular-system/datasheet-listing.html["Cisco UCS X-Series Modular System"^]



[[cisco-ucs-x-series-direct-options]]
== Opzioni Direct Cisco UCS X-Series

Cisco UCS X-Series Direct è una nuova architettura che integra una coppia di Cisco UCS Fabric Interconnect 9108 100G con Cisco UCS X9508 Chassis e Cisco UCS X-Series Compute nodes per offrire la soluzione UCS X-Series Direct.

Per una rapida panoramica delle funzionalità e delle caratteristiche di Cisco UCS X-Series, vedi link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-aag.html["Cisco UCS X-Series Direct Panoramica"^].

Cisco UCS X-Series Direct è composto dai seguenti componenti:

* Cisco UCS 9108 100G Interconnessione Fabric
* Chassis Cisco UCS X9508
* Nodi di calcolo Cisco UCS X-Series
* Componenti opzionali:
+
** Nodi PCIe e modulo X-Fabric
** Secondo chassis Cisco UCS X9508 con nodi di calcolo X-Series e moduli di fabric intelligenti Cisco UCS 9108-100G e fino a quattro server rack C-Series




Per ulteriori informazioni sui componenti della soluzione Cisco UCS X-Series Direct, consulta le specifiche tecniche di ciascuno di questi componenti nelle sezioni sopra.


NOTE: Per le specifiche tecniche complete di Cisco UCS X-Series Direct, consulta il seguente link: https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-ds.html["Cisco UCS X-Series Direct Scheda tecnica"].



[[cisco-ucs-c-series-rack-server-options]]
== Opzioni per i server rack Cisco UCS C-Series

I server rack Cisco UCS C-Series sono disponibili in versioni da una, due e quattro unità rack (RU), con varie opzioni di CPU, memoria e I/O. I codici prodotto elencati nella seconda tabella qui sotto si riferiscono al base server. Non includono CPU, memoria, unità disco, schede Peripheral Component Interconnect Express (PCIe). Sono disponibili e supportate più opzioni di configurazione nell'architettura FlexPod.

La seguente tabella elenca le opzioni di Cisco UCS C-Series rack Server.

|===
| Server rack Cisco UCS C-Series | Codice del ricambio | Specifiche tecniche 


| Cisco UCS C220 M7 | UCSC-C220-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html["Server rack Cisco UCS C220 M7"] 


| Cisco UCS C220 M8 | UCSC-C220-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html["Server rack Cisco UCS C220 M8"] 


| Cisco UCS C225 M8 | UCSC-C225-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m8-rack-server-ds.html["Server rack Cisco UCS C225 M8"] 


| Cisco UCS C240 M7 | UCSC-C240-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html["Server rack Cisco UCS C240 M7"] 


| Cisco UCS C240 M8 | UCSC-C240-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html["Server rack Cisco UCS C240 M8"] 


| Cisco UCS C245 M8 | UCSC-C245-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html["Server rack Cisco UCS C245 M8"] 
|===
La tabella seguente elenca i server rack Cisco UCS C-Series ottimizzati per casi d'uso di AI:

|===
| Server rack Cisco UCS C-Series | Codice del ricambio | Specifiche tecniche 


| Cisco UCS C845A M8 | UCSC-C845A-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c845a-m8-rack-server-ds.html["Server rack Cisco UCS C845A M8"] 


| Cisco UCS C880A M8 | UCSC-C880A-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c880a-m8-rack-server-ds.html["Server rack Cisco UCS C880A M8"] 
|===
Le generazioni precedenti di server Cisco UCS serie C possono essere utilizzate nell'architettura FlexPod se sono supportate su  https://ucshcltool.cloudapps.cisco.com/public/["Elenco di compatibilità hardware e software Cisco UCS"^].



[[cisco-nexus-9000-series-switch-options]]
== Opzioni switch Cisco Nexus serie 9000

Sono necessari switch ridondanti Cisco Nexus serie 9000 nell'architettura FlexPod. I codici prodotto elencati nella tabella sottostante si riferiscono agli chassis Cisco Nexus serie 9000; non includono moduli SFP o moduli Ethernet.

|===
| Cisco Nexus switch - Fisso | Specifiche tecniche 


| Switch Cisco Nexus serie 9200 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html["Switch Cisco Nexus serie 9200"] 


| Switch Cisco Nexus serie 9300 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html["Switch Cisco Nexus serie 9300"] 
|===
|===
| Cisco Nexus switch - Modulare | Specifiche tecniche 


| Switch Cisco Nexus serie 9400 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9400-series-switches-ds.html?ccid=cc002962&oid=dstdnc029385["Switch Cisco Nexus serie 9400"] 


| Switch Cisco Nexus serie 9500 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-729404.html["Switch Cisco Nexus serie 9500"] 


| Switch Cisco Nexus serie 9800 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9800-series-switches-ds.html?ccid=cc002962&oid=dstdnc029386["Switch Cisco Nexus serie 9800"] 
|===


[[cisco-apic-options]]
== Opzioni Cisco APIC

Cisco APIC è il principale componente architetturale di Cisco ACI. È il punto unificato di automazione e gestione per il fabric Cisco ACI.

Per ulteriori informazioni sulle specifiche del prodotto APIC, consulta la Tabella 1 fino alla Tabella 3 nella https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/application-policy-infrastructure-controller-apic/datasheet-c78-739715.html["Scheda informativa su Cisco Application Policy Infrastructure Controller"^].



[[cisco-mds-options]]
== Opzioni Cisco MDS

Sebbene gli switch Cisco MDS siano un elemento opzionale dell'architettura FlexPod, le implementazioni che utilizzano la connettività Fibre Channel SAN per un accesso allo storage ad alte prestazioni devono implementare fabric di switch Cisco MDS ridondanti per offrire un'infrastruttura SAN altamente disponibile. La tabella seguente elenca gli switch Cisco MDS supportati. Consulta la  https://imt.netapp.com["NetApp IMT"^] e la  https://ucshcltool.cloudapps.cisco.com/public/["Elenco di compatibilità hardware e software Cisco"^] per un elenco completo degli switch SAN supportati.

|===
| Switch Cisco MDS | Descrizione 


| Cisco MDS 9100 Multilayer Fabric Switches | http://www.cisco.com/c/en/us/products/storage-networking/mds-9100-series-multilayer-fabric-switches/datasheet-listing.html["Switch Cisco MDS serie 9100"] 


| Switch multiservizio Cisco MDS 9200 | https://www.cisco.com/c/en/us/products/storage-networking/mds-9200-series-multiservice-switches/datasheet-listing.html["Switch Cisco serie MDS 9200"] 


| Switch Cisco MDS 9300 Multilayer Fabric | https://www.cisco.com/c/en/us/products/storage-networking/mds-9300-series-multilayer-fabric-switches/datasheet-listing.html["Switch Cisco MDS serie 9300"] 


| Cisco MDS 9700 Multilayer Directors | http://www.cisco.com/c/en/us/products/storage-networking/mds-9700-series-multilayer-directors/datasheet-listing.html["Switch Cisco serie MDS 9700"] 
|===


[[cisco-support-licensing-options]]
== Opzioni di licenza di supporto Cisco


NOTE: Si consiglia di verificare i requisiti di licenza con il proprio rappresentante commerciale Cisco o NetApp prima di effettuare l'ordine.

link:https://www.cisco.com/c/dam/en_us/about/doing_business/legal/service_descriptions/docs/solution-support-smart-total-care.pdf["Cisco Solution Support"^] è un'offerta di Technical Support Service che si applica alle soluzioni Cisco che includono sia hardware che software di Cisco oppure di Cisco e Solution Support Alliance Partners e sono composte esclusivamente da prodotti Cisco e da prodotti forniti da vendor terzi (Solution Support Alliance Partner(s)).

Cisco supporta ambienti clienti complessi attraverso il suo link:https://www.cisco.com/c/en/us/support/web/tac/technical-services-resource-guide.html["Centro di assistenza tecnica"]. Cisco Solution Support offre ai clienti l'accesso a un team di ingegneri TAC, che fungono da principale punto di contatto per i problemi riscontrati all'interno della soluzione, nonché supporto per l'Hardware e il Software che la compongono.

Cisco sfrutta il link:https://www.tsanet.org/cisco-tsanet-case-study/["Programma partner TSANet"^] framework per integrare i Solution Support Partners in un gruppo privato sul sistema TSANet Connect. TSANet Connect offre un metodo coerente per permettere agli ingegneri del supporto di collaborare con i team tecnici dei partner, garantendo una comunicazione efficiente e una risoluzione accelerata dei problemi senza gli attriti causati da tentativi informali di lavorare con i partner
