---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, datacenter, netapp, cisco, ucs, disk shelves 
summary: Questa sezione descrive i requisiti di alimentazione e le linee guida per il cablaggio degli alloggiamenti per dischi in un progetto FlexPod Datacenter. 
---
= Linee guida per l'alimentazione e il cablaggio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa sezione descrive i requisiti di alimentazione e le linee guida per il cablaggio per una progettazione FlexPod Datacenter.



[[power-requirements]]
== Requisiti di alimentazione

I requisiti di alimentazione per il data center FlexPod variano in base alla posizione in cui è installata la configurazione del data center FlexPod.

Per ulteriori informazioni sulla potenza massima richiesta e per altre informazioni dettagliate sull'alimentazione, consultare le specifiche tecniche di ciascun componente hardware elencato nella sezione link:dc-tech-spec_technical_specifications_and_references.html["Specifiche tecniche e riferimenti: Componenti hardware"].

Per i dati dettagliati sul consumo energetico di Cisco UCS, consulta la  https://ucspowercalculator.cisco.com/["Calcolatore di alimentazione Cisco UCS"^].

Per i dati relativi all'alimentazione dello storage controller NetApp, consulta la  https://hwu.netapp.com/["NetApp Hardware Universe"^]. In *Piattaforme*, seleziona la piattaforma di storage che vuoi usare (ad esempio, AFF A90), seleziona la versione di ONTAP e poi fai clic su *Mostra risultati*. I dati relativi al cavo di alimentazione sono elencati nella sezione *Cavi di alimentazione supportati*. Per dettagli su dimensioni, peso, wattaggio ecc., consulta la sezione *Dimensioni, peso, rumorosità, alimentazione*.



[[cabling-guidelines]]
== Linee guida per il cablaggio

Questa sezione fornisce linee guida generali per il cablaggio per una progettazione FlexPod Datacenter.

* Assicurati della ridondanza della connettività per le connessioni di elaborazione e di storage.
* La velocità delle connessioni deve essere compatibile con i componenti collegati.
* Consulta la sezione link:https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_topologies.html["FlexPod Datacenter topologie"^] per ulteriori linee guida sul cablaggio per topologie specifiche.


La tabella seguente fornisce le linee guida per il cablaggio degli shelf dischi NetApp che possono essere utilizzati in una progettazione FlexPod Datacenter.

|===


| Shelf di dischi | Linee guida per il cablaggio 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["Regole di cablaggio SAS"^] 


| DS224C 


| DS460C 


| NS224 .3+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["Requisiti e best practice per gli shelf NS224 e NX224"^] 


| NS224 con NSM100B 


| NX224 
|===