---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_netapp_components.html 
keywords: storage, controllers, cluster, aff, asa, fas, afx, ontap, interconnect switches, drives, disk, shelves, licensing, options 
summary: 'I controller di storage NetApp forniscono la base dello storage nell"architettura FlexPod sia per l"avvio che per lo storage dei dati delle applicazioni. I componenti NetApp includono storage controller, switch di interconnessione cluster, shelf di dischi e dischi e opzioni di licenza.' 
---
= Componenti NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
I controller di storage NetApp forniscono la base dello storage nell'architettura FlexPod sia per l'avvio che per lo storage dei dati delle applicazioni. I componenti NetApp includono storage controller, switch di interconnessione cluster, shelf di dischi e dischi e opzioni di licenza.



[[netapp-storage-controller-options]]
== Opzioni di storage controller NetApp

Sono necessari controller FAS, AFF, ASA o AFX ridondanti NetApp nell'architettura FlexPod. I controller eseguono il software ONTAP. Quando ordini i controller di storage, puoi far preinstallare la versione software preferita sui controller. Per ONTAP, viene ordinato un cluster completo. Un cluster completo include una coppia di storage controller e un'interconnessione di cluster (con switch o senza switch).


NOTE: Una configurazione di cluster senza switch è supportata solo per un cluster a due nodi. Gli switch di interconnessione del cluster sono necessari per configurazioni con quattro o più nodi e sono opzionali per un cluster a due nodi.

Sono disponibili diverse opzioni e configurazioni, a seconda della piattaforma di storage selezionata. Per ulteriori informazioni su questi componenti aggiuntivi, rivolgersi al rappresentante di vendita.

Le famiglie di controller elencate nella tabella seguente sono adatte per l'utilizzo in una soluzione FlexPod Datacenter, in quanto la loro connessione agli switch Cisco Nexus è perfetta. Vedere https://hwu.netapp.com/["NetApp Hardware Universe"^] per informazioni specifiche sulla compatibilità di ciascun modello di controller.

|===
| Famiglia di storage NetApp per FlexPod Datacenter | Modello | Specifiche tecniche 


.6+| AFF Serie A. | AFF A20 .6+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Scheda tecnica della serie AFF A"] 


| AFF A30 


| AFF A50 


| AFF A70 


| AFF A90 


| AFF A1K 


.3+| AFF C-Series | AFF C30 .3+| https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Scheda tecnica AFF C-Series"] 


| AFF C60 


| AFF C80 


.7+| ASA | ASA A20 .7+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Scheda tecnica ASA"] 


| ASA A30 


| ASA C30 


| ASA A50 


| ASA A70 


| ASA A90 


| ASA A1K 


.5+| FAS | FAS2750 .5+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Scheda tecnica FAS"] 


| FAS2820 


| FAS50 


| FAS70 


| FAS90 


.2+| AFX | AFX 1K .2+| https://www.netapp.com/pdf.html?item=/media/142853-ds-3466-netapp-afx-datasheet.pdf["Scheda tecnica AFX"] 


| AFX 2K 
|===


[[cluster-interconnect-switch-options]]
== Opzioni switch di interconnessione cluster

La tabella seguente elenca gli switch di interconnessione del cluster Nexus disponibili per le architetture FlexPod. FlexPod supporta tutti gli switch del cluster supportati da ONTAP, inclusi gli switch non Cisco, a condizione che siano compatibili con la versione di ONTAP in fase di implementazione.

Per un elenco degli switch di interconnessione cluster supportati, vai su  https://hwu.netapp.com/["NetApp Hardware Universe"^], clicca su *Products > Networking > Switches* e poi seleziona *Cluster InterConnect Switch*. Puoi filtrare per tipo di vendor, selezionare uno switch e cliccare su *Show results* per vedere informazioni dettagliate sullo switch.

La tabella seguente elenca gli switch Cisco che puoi utilizzare come switch di interconnessione del cluster.

|===
| Switch di interconnessione del cluster | Specifiche tecniche 


| Cisco Nexus 9336C-FX2 | https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/configure-switch-overview-9336c-cluster.html["Documentazione NetApp: Switch Cisco Nexus 9336C-FX2"^] 
|===


[[netapp-disk-shelf-and-drive-options]]
== Shelf di dischi e opzioni di dischi NetApp

È necessario almeno un alloggiamento dischi NetApp per i controller di storage che non dispongono di un alloggiamento dischi integrato. Il tipo di alloggiamento NetApp selezionato determina quali tipi di unità disco sono disponibili all'interno di quell'alloggiamento.


NOTE: Per tutti gli shelf di dischi e i codici dei dischi, rivolgersi al rappresentante commerciale.

La tabella seguente elenca le opzioni di alloggiamenti per dischi NetApp per FlexPod Datacenter, insieme ai collegamenti alle relative specifiche tecniche.

Per ottenere l'elenco delle unità supportate per il tuo disk shelf, vai a link:https://hwu.netapp.com/["NetApp Hardware Universe"^], sotto *Products > Storage > Shelves* seleziona *ONTAP (AFF, ASA, FAS) o ONTAP (AFX)*, seleziona la versione di ONTAP che stai usando, poi seleziona il tipo di shelf (esempio: *DS212C*) e fai clic su *Show Results*. Fai clic su *Supported Drives* per vedere le unità supportate per versioni specifiche di ONTAP e i disk shelf.

|===
| Shelf di dischi | Specifiche tecniche 


| DS212C .6+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["Scaffali per dischi e supporti di memorizzazione"] 


| DS224C 


| DS460C 


| NS224 


| NS224 con NSM100B 


| NX224 
|===


[[netapp-software-licensing-options]]
== Opzioni di licenza software NetApp

La tabella seguente elenca le opzioni di licenza del software NetApp.

|===
| Licenze software NetApp | Specifiche tecniche 


| ONTAP One per AFF, FAS e AFX .2+| Per ulteriori informazioni sulle licenze, consulta il tuo team di vendita NetApp. 


| ONTAP One per SAN per ASA 
|===
Per ulteriori informazioni sulle licenze software NetApp, consulta il seguente link: https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licenze software NetApp"^].



[[netapp-support-licensing-options]]
== Opzioni di licenza del supporto NetApp

Le licenze SupportEdge Premium sono necessarie e i codici prodotto di queste licenze variano in base alle opzioni selezionate nel design di FlexPod Datacenter.

La tabella seguente elenca le opzioni di licenza di supporto NetApp per i sistemi di storage NetApp AFF, ASA, FAS e AFX.

|===
| Licenze NetApp Support | Specifiche tecniche 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===