---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, fas, cimc, configuration, rack, servers, ucs 
summary: In questa sezione vengono descritti i requisiti hardware minimi per le diverse versioni di FlexPod Express. 
---
= Requisiti hardware minimi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In questa sezione vengono descritti i requisiti hardware minimi per le diverse versioni di FlexPod Express.



== FlexPod Express con NetApp FAS

I requisiti hardware per le soluzioni FlexPod Express che utilizzano controller NetApp FAS per lo storage sottostante includono le configurazioni descritte in questa sezione.



=== Configurazione basata su CIMC (server rack autonomi)

La configurazione del Cisco Integrated Management Controller (CIMC) include i seguenti componenti hardware:

* Due switch Ethernet standard da 10 Gbps in configurazione ridondante (si consiglia Cisco Nexus 31108, con supporto per i modelli Cisco Nexus 3000 e 9000)
* Server rack standalone Cisco UCS C-Series
* Due controller delle serie AFF C190, AFF A250, FAS2600 o FAS 2700 in una configurazione a coppia HA (alta disponibilità) distribuiti come cluster a due nodi




=== Configurazione gestita da Cisco UCS

La conferma gestita da Cisco UCS include i seguenti componenti hardware:

* Due switch Ethernet standard da 10Gbps in configurazione ridondante (si consiglia Cisco Nexus 3524)
* Un chassis blade server Cisco UCS 5108 a corrente alternata (AC)
* Due interconnessioni fabric Cisco UCS 6324
* Server Cisco UCS B-Series (almeno quattro blade server Cisco UCS B200 M5)
* Due controller AFF C190, AFF A250, FAS2750 o FAS2720 in una configurazione di coppia HA (richiede due porte unified target adapter 2 [UTA2] disponibili per controller)




== FlexPod Express con E-Series

I requisiti hardware per la configurazione iniziale FlexPod Express con E-Series includono:

* Due interconnessioni fabric Cisco UCS 6324
* Uno chassis Cisco UCS Mini 5108 AC2 o DC2 (gli interconnettori fabric Cisco UCS 6324 sono supportati solo negli chassis AC2 e DC2)
* Server Cisco UCS B-Series (almeno due blade server Cisco UCS B200 M4)
* Una configurazione di coppia HA di un sistema storage E-Series E2824 con almeno 12 unità disco
* Due switch Ethernet standard da 10Gbps in configurazione ridondante (è possibile utilizzare gli switch già presenti nel data center)


Questi componenti hardware sono necessari per realizzare una configurazione di base della soluzione; ulteriori blade server e unità disco possono essere aggiunti in base alle esigenze. Il sistema storage E-Series E2824 può essere sostituito con una piattaforma superiore e può anche essere utilizzato come sistema all-flash.
