---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_overview.html 
keywords: flexpod, express, technical, specifications, architecture, cisco, ucs 
summary: 'FlexPod Express è un"architettura predefinita, best practice, che si basa su Cisco Unified Computing System (Cisco UCS) e sulla famiglia di switch Cisco Nexus, e il livello di storage è realizzato utilizzando NetApp FAS o NetApp E-Series storage.' 
---
= TR-4293: FlexPod Express Specifiche tecniche
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Karthick Radhakrishnan, Arvind Ramakrishnan, Lindsey Street, Savita Kumari, NetApp

[role="lead"]
FlexPod Express è un'architettura predefinita e basata sulle best practice, costruita su Cisco Unified Computing System (Cisco UCS) e sulla famiglia di switch Cisco Nexus, e il livello di storage è realizzato utilizzando NetApp FAS o lo storage NetApp E-Series. FlexPod Express è una piattaforma adatta per l'esecuzione di vari hypervisor di virtualizzazione, sistemi operativi bare metal (OS) e carichi di lavoro aziendali.

FlexPod Express offre non solo una configurazione di riferimento, ma anche la flessibilità necessaria per essere dimensionato e ottimizzato in base a diversi casi d'uso e requisiti. Questo documento classifica le configurazioni FlexPod Express in base al sistema storage utilizzato, FlexPod Express con NetApp FAS e FlexPod Express con E-Series.
