---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, flexpod, express, aff, fas, asa 
summary: In questa sezione vengono descritti i requisiti di connettività per le diverse versioni di FlexPod Express. 
---
= Requisiti di connettività
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In questa sezione vengono descritti i requisiti di connettività per le diverse versioni di FlexPod Express.



== Requisiti di connettività per FlexPod Express con NetApp AFF/ ASA/ FAS

I requisiti di connettività per FlexPod Express con NetApp AFF/ ASA/ FAS includono:

* NetApp I controller di storage devono essere collegati direttamente agli switch Cisco Nexus.
* Per le implementazioni UCS X-series Direct, i NetApp storage controller possono essere collegati direttamente ai Fabric Interconnect integrati.
* Non è possibile posizionare in linea apparecchiature aggiuntive tra i componenti principali di FlexPod.
* I virtual port channel (vPC) sono necessari per collegare gli switch Cisco Nexus serie 9000 ai controller di storage NetApp.
* Sebbene non sia necessario, si consiglia di abilitare il supporto dei frame jumbo in tutto l'ambiente.

