---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, flexpod, express, aff, fas, asa 
summary: In questa sezione vengono descritti i requisiti di connettività per le diverse versioni di FlexPod Express. 
---
= Requisiti di connettività
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Questa sezione descrive i requisiti generali di connettività per le diverse versioni di FlexPod Express.



== Requisiti di connettività per FlexPod Express con NetApp AFF/ ASA/ FAS

I requisiti di connettività per FlexPod Express con NetApp AFF/ ASA/ FAS generalmente includono:

* NetApp I controller di storage devono essere collegati direttamente agli switch Cisco Nexus.
* Per le implementazioni Cisco UCS X-Series Direct, i controller di storage NetApp possono essere collegati direttamente ai Fabric Interconnect integrati.
* Non è possibile posizionare in linea apparecchiature aggiuntive tra i componenti principali di FlexPod.
* I virtual port channel (vPC) sono necessari per collegare gli switch Cisco Nexus serie 9000 ai controller di storage NetApp.
* Sebbene non sia necessario, si consiglia di abilitare il supporto dei frame jumbo in tutto l'ambiente.


Consulta la sezione link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_flexpod_express_topologies.html["FlexPod Express topologie"^] per i requisiti di connettività specifici per ciascuna topologia.
