---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec__netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: 'NetApp storage controller forniscono la base storage nell"architettura FlexPod Express sia per lo storage di avvio che per lo storage dei dati delle applicazioni. Questa sezione elenca le diverse opzioni di storage NetApp nell"architettura FlexPod Express.' 
---
= Componenti NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
I controller di storage NetApp forniscono la base dello storage nell'architettura FlexPod Express per l'avvio e lo storage dei dati delle applicazioni. Questa sezione elenca le diverse opzioni NetApp nell'architettura FlexPod Express.



== Opzioni di storage controller NetApp

Sono necessari controller ridondanti delle serie AFF, ASA o FAS nell'architettura FlexPod Express. I controller eseguono il software ONTAP. Al momento dell'ordine dei controller di storage, la versione software preferita può essere precaricata sui controller. Per ONTAP, il cluster può essere implementato sia con una coppia di switch di interconnessione del cluster, sia in una configurazione di cluster senza switch.


NOTE: Una configurazione di cluster senza switch è supportata solo per una configurazione a due nodi. Gli switch di interconnessione del cluster sono necessari per configurazioni con più di 4 nodi e sono opzionali per una configurazione a due nodi.

A seconda della piattaforma di storage selezionata, sono disponibili diverse opzioni e configurazioni. Consultare il proprio rappresentante commerciale per dettagli su questi componenti aggiuntivi.

Le famiglie di controller elencate nella tabella sottostante sono adatte all'utilizzo in una soluzione FlexPod perché la loro connessione agli switch Cisco Nexus è trasparente. Consultare la  http://hwu.netapp.com/["NetApp Hardware Universe"^] per i dettagli specifici sulla compatibilità di ciascun modello di controller.

|===
| NetApp entry-level storage Family per FlexPod Express | Modello | Specifiche tecniche 


.2+| AFF Serie A. | A20 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Documentazione di AFF A-Series"] 


| A30 


| AFF C-Series | C30 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Documentazione AFF C-Series"] 


.2+| ASA A-Series | A20 .2+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Documentazione ASA A-Series"] 


| A30 


| ASA C-Series | C30 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Documentazione ASA C-Series"] 


.2+| FAS | FAS 2750 .2+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Documentazione FAS"] 


| FAS 2820 
|===


== Shelf di dischi e dischi NetApp

Per i controller di archiviazione è necessario almeno un alloggiamento per dischi NetApp.

Il tipo di shelf NetApp selezionato determina i tipi di dischi disponibili all'interno di tale shelf.


NOTE: Per tutti gli shelf di dischi e i codici dei dischi, rivolgersi al rappresentante commerciale.

Per ulteriori informazioni sulle unità supportate, fare clic sul collegamento NetApp Hardware Universe nella tabella seguente, quindi selezionare unità supportate.

La seguente tabella elenca le opzioni di shelf di dischi NetApp, insieme ai dischi supportati per ciascun tipo di shelf, disponibili su NetApp Hardware Universe. Seguire il link Hardware Universe, selezionare la versione di ONTAP in uso, quindi selezionare il tipo di shelf. Sotto l'immagine shelf, fare clic su Supported Drives (unità supportate) per visualizzare le unità supportate per versioni specifiche di ONTAP e gli shelf di dischi.

|===
| Shelf di dischi | Specifiche tecniche 


| DS212C .5+| https://hwu.netapp.com/DetailViews/Home.aspx["Shelf di dischi e supporti di storage supportati su NetApp Hardware Universe"] 


| DS224C 


| DS460C 


| NS224 


| NS224 con NSM100B 
|===


== Opzioni di licenza software NetApp

La tabella seguente elenca le opzioni di licenza del software NetApp.

|===
| Licenze software NetApp | Specifiche tecniche 


| ONTAP One o ONTAP base per AFF e FAS .2+| Per ulteriori informazioni sulle licenze, consulta il tuo team di vendita NetApp. 


| ONTAP One per SAN per ASA 
|===


== Opzioni di licenza del supporto NetApp

Sono necessarie licenze SupportEdge Premium e i codici prodotto di tali licenze variano in base alle opzioni selezionate nella progettazione FlexPod.

La tabella seguente elenca le opzioni di licenza di supporto NetApp per i sistemi di storage NetApp AFF, ASA e FAS.

|===
| Licenze NetApp Support | Codice del ricambio | Specifiche tecniche 


| SupportEdge Premium4 ore on-site; mesi: 36 | CS-O2-4HR | link:https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf["https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf"] 
|===