---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_technical_specifications_and_references.html 
keywords: technical, specifications, references, servers, ucs, rack, disk, shelves, aff, asa, fas, x-series-direct, c-series, adapters, controllers 
summary: Questa sezione descrive specifiche tecniche importanti aggiuntive per ciascun componente FlexPod Express. 
---
= Specifiche tecniche e riferimenti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Questa sezione descrive specifiche tecniche importanti aggiuntive per ciascun componente FlexPod Express.



[[cisco-ucs-x-series-direct-chassis]]
== Chassis Cisco UCS X-Series Direct

Le specifiche tecniche dello chassis Cisco UCS X-Series Direct, come mostrato nella tabella sottostante, includono i seguenti componenti:

* Numero di unità rack
* Numero massimo di nodi
* Funzionalità Unified Fabric
* Numero di alloggiamenti i/o per gli IFM


|===
| Componente | chassis Cisco UCS X9508 


| Unità rack | 7 


| Numero massimo di nodi | 8 


| Capacità di Unified Fabric | Sì 


| Alloggiamenti i/o per IFM | Due alloggiamenti per Cisco UCS 9108 Intelligent Fabric Modules (IFM) 
|===
Per ulteriori informazioni, consultare link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html["Scheda informativa sullo chassis Cisco UCS X9508 X-Series"^].



[[cisco-ucs-x-series-direct-compute-node]]
== Nodo di elaborazione diretto Cisco UCS X-Series

Le specifiche tecniche del nodo di calcolo Cisco UCS X-Series includono i seguenti componenti:

* Numero di socket del processore
* Supporto del processore
* Capacità di memoria
* Dimensioni e velocità
* Supporto per l'avvio SAN
* Numero di slot per schede mezzanine
* Throughput i/o massimo
* Fattore di forma
* Numero massimo di nodi di calcolo per chassis


Consulta la tabella qui sotto per le specifiche tecniche dei nodi di elaborazione Cisco UCS X-Series Direct.

|===


| Componente | Scheda informativa Cisco UCS 


| Cisco UCS X210c M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html["Nodo di calcolo Cisco UCS X210c M7"] 


| Cisco UCS X210c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html["Nodo di calcolo Cisco UCS X210c M8"] 


| Cisco UCS X215c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html["Nodo di calcolo Cisco UCS X215c M8"] 


| Cisco UCS X410c M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html["Nodo di calcolo Cisco UCS X410c M7"] 


| Cisco UCS X410c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html["Nodo di calcolo Cisco UCS X410c M8"] 
|===


[[cisco-ucs-x-series-direct-fabric-interconnect]]
== Cisco UCS X-Series Direct fabric interconnect

Le specifiche tecniche per Cisco UCS X-Series Direct fabric interconnect includono form factor, numero totale di porte e slot di espansione, e capacità di throughput. Consulta la tabella qui sotto per la scheda tecnica di Cisco UCS X-Series Direct fabric interconnect.

|===
| Componente | Scheda informativa Cisco UCS 


| Cisco UCS 9108 100G Interconnessione Fabric | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf["Cisco UCS 9108 100G Interconnessione Fabric"] 
|===


[[cisco-ucs-xe9305-chassis-cisco-unified-edge]]
== Chassis Cisco UCS XE9305 (Cisco Unified Edge)

Le specifiche tecniche dello chassis Cisco UCS XE9305, come mostrato nella tabella sottostante, includono i seguenti componenti:

|===
| Componente | chassis Cisco UCS XE9305 


| Unità rack | 3 


| Numero massimo di nodi | 5 Cisco UCS XE130c M8 Compute Nodes o 2 Cisco UCS XE150c M8 Compute Nodes 
|===
Per ulteriori informazioni, vedere il link:https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-xe9305-m8-chassis-spec-sheet.pdf["Scheda tecnica dello chassis Cisco UCS XE9305"^].



[[cisco-ucs-compute-nodes-for-cisco-unified-edge]]
== Nodi di calcolo Cisco UCS per Cisco Unified Edge

Le specifiche tecniche dei nodi di calcolo Cisco UCS per Cisco Unified Edge includono i seguenti componenti:

* Numero di socket del processore
* Supporto del processore
* Supporto GPU
* Capacità di memoria
* Dimensioni e velocità
* Throughput i/o massimo
* Fattore di forma


I nodi di calcolo supportano anche le GPU: XE130c M8 supporta la GPU NVIDIA L4 e XE150c M8 supporta le GPU NVIDIA RTX PRO 4500 / 6000 Blackwell Server Edition. Consulta la tabella qui sotto per le specifiche tecniche dei nodi di calcolo Cisco UCS Unified Edge.

|===


| Componente | Scheda informativa Cisco UCS 


| Nodo di calcolo Cisco UCS XE130c M8 | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-xe130c-m8-compute-node-spec-sheet.pdf["Nodo di calcolo Cisco UCS XE130c M8"] 


| Nodo di calcolo Cisco UCS XE150c M8 | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/unified-edge/cisco-ucs-xe150c-m8-compute-node.pdf["Nodo di calcolo Cisco UCS XE150c M8"] 
|===
Per ulteriori dettagli, fai riferimento a link:https://www.cisco.com/c/en/us/products/servers-unified-computing/unified-edge/datasheet-listing.html["Elenco delle schede tecniche di Cisco Unified Edge"^].



[[cisco-ucs-c-series-rack-servers]]
== Server rack Cisco UCS C-Series

Le specifiche tecniche dei server rack Cisco UCS C-Series includono il supporto dei processori, la capacità massima di memoria, il numero di slot PCIe e il form factor. Per ulteriori dettagli sui modelli di server UCS compatibili, consulta l' https://ucshcltool.cloudapps.cisco.com/public/["Compatibilità hardware Cisco"^]elenco.

Consulta la tabella qui sotto per le specifiche tecniche dei server rack Cisco UCS C-Series.

|===
| Componente | Scheda informativa Cisco UCS 


| Cisco UCS C220 M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html["Server rack Cisco UCS C220 M7"] 


| Cisco UCS C220 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html["Server rack Cisco UCS C220 M8"] 


| Cisco UCS C225 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m8-rack-server-ds.html["Server rack Cisco UCS C225 M8"] 


| Cisco UCS C240 M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html["Server rack Cisco UCS C240 M7"] 


| Cisco UCS C240 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html["Server rack Cisco UCS C240 M8"] 


| Cisco UCS C245 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html["Server rack Cisco UCS C245 M8"] 
|===


[[cisco-nexus-switches]]
== Switch Cisco Nexus

Le specifiche tecniche degli switch Cisco Nexus sono contenute nella scheda tecnica di ciascun modello. Le specifiche includono il form factor, il numero di supervisor, moduli fabric e slot per schede di linea, e il numero massimo di porte. Queste schede tecniche sono reperibili nella tabella seguente.

|===
| Componente | Scheda informativa su Cisco Nexus 


| Cisco Nexus serie 9200 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html["Switch Cisco Nexus serie 9200"] 


| Cisco Nexus serie 9300 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html["Switch Cisco Nexus serie 9300"] 
|===


[[netapp-storage-controllers]]
== Storage controller NetApp

Le specifiche tecniche per i controller di storage NetApp includono la configurazione della piattaforma, la capacità raw massima, la memoria, il form factor, i requisiti della versione di ONTAP, gli shelf di dischi, ecc.



[[netapp-aff-a-series]]
=== NetApp AFF A-Series

I controller di storage AFF serie A di livello base NetApp sono supportati per l'utilizzo in FlexPod Express. Ulteriori informazioni sono disponibili nella  https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Specifiche tecniche della serie AFF A"^] scheda tecnica e nella  https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consulta la documentazione specifica della piattaforma elencata nella tabella seguente per informazioni dettagliate su uno specifico modello AFF.

|===
| Componente | Documentazione sulla piattaforma del controller AFF Serie A. 


| NetApp AFF A20 | https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a20-key-specifications.html#aff-a20-specifications-at-a-glance["Specifiche principali di AFF A20"] 


| NetApp AFF A30 | https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a30-key-specifications.html#aff-a30-specifications-at-a-glance["Specifiche principali di AFF A30"] 
|===


[[netapp-aff-c-series]]
=== NetApp AFF C-Series

I controller di storage NetApp AFF C-Series di livello base sono supportati per l'utilizzo in FlexPod Express. Ulteriori informazioni sono disponibili nella https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Specifiche tecniche della serie AFF C"^] scheda tecnica e nella https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consulta la documentazione specifica della piattaforma elencata nella tabella seguente per informazioni dettagliate su uno specifico modello AFF.

|===
| Componente | Documentazione della piattaforma storage controller AFF C-Series 


| NetApp AFF C30 | https://docs.netapp.com/us-en/ontap-systems/c30-60/c30-key-specifications.html["Specifiche principali di AFF C30"] 
|===


[[netapp-asa]]
=== NetApp ASA

I modelli entry-level dei controller di storage NetApp ASA sono supportati per l'utilizzo in FlexPod Express. Ulteriori informazioni sono disponibili nella https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA Specifiche tecniche"^] scheda tecnica e nella https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consulta la documentazione specifica della piattaforma elencata nella tabella seguente per informazioni dettagliate su un modello ASA specifico.

|===
| Componente | NetApp Documentazione della piattaforma controller ASA 


| NetApp ASA A20 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a20-key-specifications.html["Specifiche chiave ASA A20"] 


| NetApp ASA A30 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a30-key-specifications.html["ASA A30 Specifiche principali"] 


| NetApp ASA C30 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Specifiche principali di ASA C30"] 
|===


[[netapp-fas-series]]
=== NetApp serie FAS

I controller di storage FAS di livello base sono supportati per l'utilizzo in un FlexPod Express. Le specifiche dettagliate per tutti i controller di storage della serie FAS sono disponibili nella  https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consulta la documentazione specifica della piattaforma elencata nella tabella seguente per informazioni dettagliate su uno specifico modello FAS.

|===
| Componente | Documentazione sulla piattaforma controller della serie FAS 


| Serie FAS2750 | https://docs.netapp.com/us-en/ontap-systems/fas2700/overview.html["FAS2750 Specifiche chiave"^] 


| Serie FAS2820 | https://docs.netapp.com/us-en/ontap-systems/fas2800/overview.html["Specifiche chiave di FAS2820"^] 


| Serie FAS50 | https://docs.netapp.com/us-en/ontap-systems/fas50/overview.html["Specifiche chiave di FAS50"^] 
|===


[[netapp-disk-shelves]]
=== Shelf di dischi NetApp

Le specifiche tecniche per NetApp disk shelves includono il form factor, il numero di unità per alloggiamento e i moduli I/O dell'alloggiamento; questa documentazione è reperibile nella tabella seguente. Per ulteriori informazioni, consulta il  https://hwu.netapp.com/["NetApp Hardware Universe"^].

|===
| Componente | Documentazione sugli shelf di dischi NetApp FAS/AFF 


| Shelf di dischi NetApp DS212C | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentazione shelf di dischi DS212C"] 


| Shelf di dischi NetApp DS224C | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentazione sugli shelf di dischi DS224C"] 


| Shelf di dischi NetApp DS460C | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentazione sugli shelf di dischi DS460C"] 


| Shelf di dischi NetApp NS224 | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentazione shelf di dischi NS224"] 


| NS224 con shelf per dischi NSM 100B | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentazione del disk shelf NS224 con NSM 100B"] 
|===


[[netapp-drives]]
=== Dischi NetApp

Le specifiche tecniche dei dischi NetApp includono dimensioni del fattore di forma, capacità del disco, rpm del disco, controller di supporto e requisiti di versione ONTAP. Queste specifiche sono disponibili nella sezione Drives (unità) di http://hwu.netapp.com/Drives/Index?queryId=1581392["NetApp Hardware Universe"^].
