---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: 'NetApp storage controller forniscono la base storage nell"architettura FlexPod Express sia per lo storage di avvio che per lo storage dei dati delle applicazioni. Questa sezione elenca le diverse opzioni di storage NetApp nell"architettura FlexPod Express.' 
---
= Componenti NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
I controller di storage NetApp forniscono la base dello storage nell'architettura FlexPod Express per l'avvio e lo storage dei dati delle applicazioni. Questa sezione elenca le diverse opzioni NetApp nell'architettura FlexPod Express.



== Opzioni di storage controller NetApp

Sono necessari controller ridondanti delle serie AFF, ASA o FAS nell'architettura FlexPod Express. I controller eseguono il software ONTAP. Al momento dell'ordine dei controller di storage, la versione software preferita può essere precaricata sui controller. Per ONTAP, il cluster può essere implementato sia con una coppia di switch di interconnessione del cluster, sia in una configurazione di cluster senza switch.


NOTE: Una configurazione di cluster senza switch è supportata solo per una configurazione a due nodi. Gli switch di interconnessione del cluster sono necessari per configurazioni con più di 4 nodi e sono opzionali per una configurazione a due nodi.

Sono disponibili diverse opzioni e configurazioni a seconda della piattaforma di storage selezionata. Consultare il proprio referente commerciale per dettagli su questi componenti aggiuntivi.

Le famiglie di controller elencate nella tabella sottostante sono adatte all'utilizzo in una soluzione FlexPod perché la loro connessione agli switch Cisco Nexus è trasparente. Consultare la  http://hwu.netapp.com/["NetApp Hardware Universe"^] per i dettagli specifici sulla compatibilità di ciascun modello di controller.

|===
| NetApp entry-level storage Family per FlexPod Express | Modello | Specifiche tecniche 


.2+| AFF Serie A. | A20 .3+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Documentazione AFF"] 


| A30 


| AFF C-Series | C30 


.2+| ASA A-Series | A20 .3+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Documentazione ASA"] 


| A30 


| ASA C-Series | C30 


.2+| FAS | FAS 2750 .2+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Documentazione FAS"] 


| FAS 2820 
|===


== Shelf di dischi e dischi NetApp

Per i controller di archiviazione è necessario almeno un alloggiamento per dischi NetApp.

Il tipo di shelf NetApp selezionato determina i tipi di dischi disponibili all'interno di tale shelf.


NOTE: Per tutti gli shelf di dischi e i codici dei dischi, rivolgersi al rappresentante commerciale.

La tabella seguente elenca le opzioni di shelf di dischi NetApp per FlexPod Express, insieme ai collegamenti alle relative specifiche tecniche.

Per ottenere l'elenco delle unità supportate per il tuo disk shelf, vai a link:https://hwu.netapp.com/DetailViews/Home.aspx["NetApp Hardware Universe"^], sotto *Products > Storage > Shelves* seleziona *ONTAP (AFF, ASA, FAS)*, seleziona la versione di ONTAP che stai utilizzando, poi seleziona il tipo di shelf (esempio: *DS212C*) e fai clic su *Show Results*. Fai clic su *Supported Drives* per vedere le unità supportate per specifiche versioni di ONTAP e i disk shelf.

|===
| Shelf di dischi | Specifiche tecniche 


| DS212C .5+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["Scaffali per dischi e supporti di memorizzazione"] 


| DS224C 


| DS460C 


| NS224 


| NS224 con NSM100B 
|===


== Opzioni di licenza software NetApp

La tabella seguente elenca le opzioni di licenza del software NetApp.

|===
| Licenze software NetApp | Specifiche tecniche 


| ONTAP One per AFF e FAS .2+| Per ulteriori informazioni sulle licenze, consulta il tuo team di vendita NetApp. 


| ONTAP One per SAN per ASA 
|===
Per ulteriori informazioni sulle licenze software NetApp, consulta questo link: https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licenze software NetApp"^].



== Opzioni di licenza del supporto NetApp

Sono necessarie licenze SupportEdge Premium e i codici prodotto di tali licenze variano in base alle opzioni selezionate nella progettazione FlexPod.

La tabella seguente elenca le opzioni di licenza di supporto NetApp per i sistemi di storage NetApp AFF, ASA e FAS.

|===
| Licenze NetApp Support | Specifiche tecniche 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===