---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, express, cisco, ucs, cabling 
summary: Questa sezione descrive i requisiti di alimentazione e le linee guida per il cablaggio degli alloggiamenti per dischi in un design FlexPod Express. 
---
= Linee guida per l'alimentazione e il cablaggio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Questa sezione descrive i requisiti di alimentazione e le linee guida per il cablaggio di un design FlexPod Express.



== Requisiti di alimentazione

I requisiti di alimentazione per FlexPod Express variano in base alla posizione in cui viene installata la configurazione FlexPod Express.

Per ulteriori dati sulla potenza massima richiesta e per altre informazioni dettagliate sulla potenza, consulta la link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_technical_specifications_and_references.html["specifiche tecniche"^] per ciascun componente hardware.

Per informazioni dettagliate sull'alimentazione di Cisco UCS, consultare la http://www.cisco.com/assets/cdc_content_elements/flash/dataCenter/cisco_ucs_power_calculator/["Calcolatore di alimentazione Cisco UCS"^].

Per i dati relativi all'alimentazione dello storage controller NetApp, consulta la  http://hwu.netapp.com/Controller/Index?platformTypeId=6780858["NetApp Hardware Universe"^]. In *Piattaforme*, seleziona la piattaforma di storage che vuoi usare (ad esempio, AFF A20), seleziona la versione di ONTAP e poi fai clic su *Mostra risultati*. I dati relativi al cavo di alimentazione sono elencati nella sezione *Cavi di alimentazione supportati* e per dettagli su dimensioni, peso, potenza ecc. fai riferimento alla sezione *Dimensioni, peso, rumorosità, alimentazione*.



== Linee guida per il cablaggio

Questa sezione fornisce linee guida generali per il cablaggio di un design FlexPod Express.

* Assicurati della ridondanza della connettività per le connessioni di elaborazione e di storage.
* La velocità delle connessioni deve essere compatibile con i componenti collegati.
* Consulta la sezione link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_flexpod_express_topologies.html["FlexPod Express topologie"^] per ulteriori linee guida sul cablaggio per topologie specifiche.


La tabella seguente fornisce le linee guida per il cablaggio degli shelf di dischi NetApp che possono essere utilizzati in una progettazione FlexPod Express.

|===


| Shelf di dischi | Linee guida per il cablaggio 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["Regole di cablaggio SAS"^] 


| DS224C 


| DS460C 


| NS224 .2+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["Requisiti e best practice per lo shelf NS224"^] 


| NS224 con NSM100B 
|===