---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_minimum_software_requirements.html 
keywords: minimum, software, requirements, flexpod, express, aff, fas, e, series 
summary: In questa sezione vengono descritti i requisiti software minimi per le diverse versioni di FlexPod Express. 
---
= Requisiti software minimi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In questa sezione vengono descritti i requisiti software minimi per le diverse versioni di FlexPod Express.



== Requisiti software per FlexPod Express con NetApp AFF/ ASA/ FAS

I requisiti software per il FlexPod Express con NetApp AFF/ ASA/ FAS includono:

* ONTAP 9.16 o versioni successive
* Cisco NX-OS versione 10.4(6)M o successiva



NOTE: Tutte le versioni software elencate in questa sezione rappresentano i requisiti minimi per i componenti hardware (NetApp e Cisco) elencati nelle sezioni successive del documento.

Tutti i software devono essere elencati e supportati in http://support.netapp.com/matrix/["NetApp IMT"^]. Alcune funzionalità software potrebbero richiedere versioni di codice più recenti rispetto ai valori minimi elencati nelle architetture precedenti.
