---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_overview.html 
keywords: flexpod, express, technical, specifications, architecture, cisco, ucs, netapp, aff, asa, fas 
summary: 'FlexPod Express è un"architettura predefinita e best practice, basata su Cisco Unified Computing System (Cisco UCS) e sulla famiglia di switch Cisco Nexus, mentre il livello di storage è realizzato utilizzando i sistemi di storage NetApp AFF, ASA o FAS.' 
---
= Specifiche tecniche di FlexPod Express
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
FlexPod Express è un'architettura predefinita e best practice, costruita su Cisco Unified Computing System (Cisco UCS) e sulla famiglia di switch Cisco Nexus, e il livello di storage è realizzato utilizzando i sistemi di storage entry-level NetApp AFF, ASA o FAS. FlexPod Express è una piattaforma adatta per eseguire vari hypervisor di virtualizzazione, sistemi operativi bare metal (OS) e carichi di lavoro aziendali in ambienti di piccole e medie dimensioni, implementazioni ROBO (uffici remoti e filiali) e sedi periferiche.

FlexPod Express offre non solo una configurazione di riferimento, ma anche la flessibilità necessaria per essere dimensionato e ottimizzato in base a diversi casi d'uso e requisiti.
