---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec__netapp_components.html 
keywords: storage, controller, options, fas, e, series, disk, shelves, licensing, software 
summary: 'I controller di storage NetApp forniscono la base dello storage nell"architettura FlexPod Express per l"avvio e lo storage dei dati delle applicazioni. Questa sezione elenca le diverse opzioni NetApp nell"architettura FlexPod Express.' 
---
= Componenti NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
I controller di storage NetApp forniscono la base dello storage nell'architettura FlexPod Express per l'avvio e lo storage dei dati delle applicazioni. Questa sezione elenca le diverse opzioni NetApp nell'architettura FlexPod Express.



== Opzioni di storage controller NetApp



== NetApp FAS

Sono necessari controller ridondanti delle serie AFF C190, AFF A220 o FAS2750 nell'architettura FlexPod Express. I controller eseguono il software ONTAP. Al momento dell'ordine dei controller di storage, la versione software preferita può essere precaricata sui controller. Per ONTAP, il cluster può essere implementato sia con una coppia di switch di interconnessione del cluster, sia in una configurazione di cluster senza switch.

I codici articolo elencati nella tabella seguente si riferiscono a un controller vuoto. Sono disponibili diverse opzioni e configurazioni a seconda della piattaforma di storage selezionata. Consultare il proprio referente commerciale per dettagli su questi componenti aggiuntivi.

|===
| Controller dello storage | Codice ricambio FAS | Specifiche tecniche 


| FAS2750 | In base alle singole opzioni scelte | https://www.netapp.com/us/products/storage-systems/hybrid-flash-array/fas2700.aspx[] 


| FAS2720 | In base alle singole opzioni scelte | https://www.netapp.com/us/products/storage-systems/hybrid-flash-array/fas2700.aspx[] 


| AFF C190 | In base alle singole opzioni scelte | https://www.netapp.com/us/products/entry-level-aff.aspx[] 


| AFF A220 | In base alle singole opzioni scelte | https://www.netapp.com/us/documentation/all-flash-fas.aspx[] 


| FAS2620 | In base alle singole opzioni scelte | http://www.netapp.com/us/products/storage-systems/fas2600/fas2600-tech-specs.aspx[] 


| FAS2650 | In base alle singole opzioni scelte | http://www.netapp.com/us/products/storage-systems/fas2600/fas2600-tech-specs.aspx[] 
|===


=== storage E-Series

È necessaria una coppia HA di controller della serie NetApp E2800 nell'architettura FlexPod Express. I controller eseguono il SANtricity OS.

I codici articolo elencati nella tabella seguente si riferiscono a un controller vuoto. Sono disponibili diverse opzioni e configurazioni a seconda della piattaforma di storage selezionata. Consultare il proprio referente commerciale per dettagli su questi componenti aggiuntivi.

|===
| Controller dello storage | Codice del ricambio | Specifiche tecniche 


| E2800 | In base alle singole opzioni scelte | http://www.netapp.com/us/products/storage-systems/e2800/e2800-tech-specs.aspx[] 
|===


== NetApp moduli di espansione Ethernet



=== NetApp FAS

La tabella seguente elenca le opzioni dell'adattatore NetApp FAS10GbE.

|===
| Componente | Codice del ricambio | Specifiche tecniche 


| NetApp X1117A | X1117A-R6 | https://library.netapp.com/ecm/ecm_download_file/ECMM1280307[] 
|===
[NOTE]
====
I sistemi storage delle serie FAS2500 e 2600 dispongono di porte 10GbE integrate.

L'adattatore NetApp X1117A è per i sistemi storage FAS8020.

====


=== storage E-Series

La tabella seguente elenca le opzioni degli adattatori 10GbE E-Series.

|===
| Componente | Codice del ricambio 


| 10GbE iSCSI/16Gb FC 4 porte | X-56025-00-0E-C. 


| 10GbE iSCSI/16Gb FC a 2 porte | X-56024-00-0E-C. 
|===
[NOTE]
====
I sistemi di storage della serie E2824 sono dotati di porte 10GbE integrate.

La scheda di interfaccia host (HIC) a 4 porte 10GbE iSCSI/16Gb FC può essere utilizzata per una maggiore densità di porte.

====
Le porte integrate e l'HIC possono funzionare come adattatori iSCSI o adattatori FC a seconda della funzione attivata in SANtricity OS.

Per ulteriori informazioni sulle opzioni di adattatori supportate, consultare la sezione Adattatori di  https://hwu.netapp.com/Adapter/Index["NetApp Hardware Universe"^].



== Shelf di dischi e dischi NetApp



== NetApp FAS

È necessario almeno un alloggiamento dischi NetApp per i controller di storage. Il tipo di alloggiamento NetApp selezionato determina quali tipi di unità sono disponibili all'interno di quell'alloggiamento.

Le serie di controller FAS2700 e FAS2600 sono disponibili in una configurazione che include due controller di storage e dischi alloggiati nello stesso chassis. Questa configurazione è offerta con unità SATA o SAS; pertanto, non sono necessari ulteriori shelf di dischi esterni, a meno che le esigenze di prestazioni o capacità non richiedano un numero maggiore di dischi.

[NOTE]
====
Tutti i codici articolo degli alloggiamenti per dischi si riferiscono all'alloggiamento vuoto con due alimentatori CA. Per ulteriori codici articolo, consultare il proprio rappresentante commerciale.

I codici articolo delle unità disco variano in base alle dimensioni e al form factor del disco che si intende acquistare. Consultare il proprio rappresentante commerciale per ulteriori codici articolo.

====
La seguente tabella elenca le opzioni di shelf di dischi NetApp, insieme ai dischi supportati per ciascun tipo di shelf, disponibili su NetApp Hardware Universe. Seguire il link Hardware Universe, selezionare la versione di ONTAP in uso, quindi selezionare il tipo di shelf. Sotto l'immagine shelf, fare clic su Supported Drives (unità supportate) per visualizzare le unità supportate per versioni specifiche di ONTAP e gli shelf di dischi.

|===
| Shelf di dischi | Codice del ricambio | Specifiche tecniche 


| DS212C | DS212C-0-12 | link:http://www.netapp.com/us/products/storage-systems/disk-shelves-and-storage-media/disk-shelves-tech-specs.aspx["Specifiche tecniche di shelf di dischi e supporti di memorizzazione Unità supportate su NetApp Hardware Universe"] 


| DS224C | DS224C-0-24 | link:http://www.netapp.com/us/products/storage-systems/disk-shelves-and-storage-media/disk-shelves-tech-specs.aspx["Specifiche tecniche di shelf di dischi e supporti di memorizzazione Unità supportate su NetApp Hardware Universe"] 


| DS460C | DS460C-0-60 | link:http://www.netapp.com/us/products/storage-systems/disk-shelves-and-storage-media/disk-shelves-tech-specs.aspx["Specifiche tecniche di unità disco e supporti di memorizzazione Unità supportate su NetApp Hardware Universe"] 


| DS2246 | X559A-R6 | link:http://www.netapp.com/us/products/storage-systems/disk-shelves-and-storage-media/disk-shelves-tech-specs.aspx["Specifiche tecniche di unità disco e supporti di memorizzazione Unità supportate su NetApp Hardware Universe"] 


| DS4246 | X24M-R6 | link:http://www.netapp.com/us/products/storage-systems/disk-shelves-and-storage-media/disk-shelves-tech-specs.aspx["Specifiche tecniche di unità disco e supporti di memorizzazione Unità supportate su NetApp Hardware Universe"] 


| DS4486 | DS4486-144TB-R5-C | link:http://www.netapp.com/us/products/storage-systems/disk-shelves-and-storage-media/disk-shelves-tech-specs.aspx["Specifiche tecniche di unità disco e supporti di memorizzazione Unità supportate su NetApp Hardware Universe"] 
|===


=== storage E-Series

È necessario almeno uno shelf NetApp per i controller di storage che non ospitano unità disco nel loro chassis. Il tipo di shelf NetApp selezionato determina quali tipi di unità sono disponibili all'interno di quello shelf.

I controller della serie E2800 sono offerti in una configurazione che include due controller di storage più dischi alloggiati in un alloggiamento per dischi supportato. Questa configurazione è offerta con unità SSD o SAS.


NOTE: I codici articolo delle unità disco variano in base alle dimensioni e al form factor del disco che si intende acquistare. Consultare il proprio rappresentante commerciale per ulteriori codici articolo.

La tabella seguente elenca le opzioni di shelf per dischi NetApp e le unità supportate per ciascun tipo di shelf, che possono essere trovate su NetApp Hardware Universe. Segui il link di Hardware Universe, seleziona la versione di ONTAP in uso, quindi seleziona il tipo di shelf. Sotto l'immagine dello shelf, fai clic su Supported Drives per vedere le unità supportate per specifiche versioni di ONTAP e per i disk shelf.

|===
| Shelf di dischi | Codice del ricambio | Specifiche tecniche 


| DE460C | E-X5730A-DM-0E-C | link:http://www.netapp.com/us/products/storage-systems/e2800/e2800-tech-specs.aspx["Shelf di dischi specifiche tecniche unità supportate su NetApp Hardware Universe"] 


| DE224C | E-X5721A-DM-0E-C | link:http://www.netapp.com/us/products/storage-systems/e2800/e2800-tech-specs.aspx["Shelf di dischi specifiche tecniche unità supportate su NetApp Hardware Universe"] 


| DE212C | E-X5723A-DM-0E-C | link:https://hwu.netapp.com/Shelves/Index?osTypeId=2357027["Shelf di dischi specifiche tecniche unità supportate su NetApp Hardware Universe"] 
|===


== Opzioni di licenza software NetApp



=== NetApp FAS

La tabella seguente elenca le opzioni di licenza del software NetApp FAS.

|===
| Licenze software NetApp | Codice ricambio | Specifiche tecniche 


| Licenza cluster di base 2+| Per ulteriori informazioni sulle licenze, consulta il tuo team di vendita NetApp. 
|===


=== storage E-Series

La tabella seguente elenca le opzioni di licenza software E-Series.

|===
| Licenze software NetApp | Codice del ricambio | Specifiche tecniche 


| Caratteristiche standard 2.2+| Per ulteriori informazioni sulle licenze, consulta il tuo team di vendita NetApp. 


| Funzionalità premium 
|===


== Opzioni di licenza del supporto NetApp

Sono necessarie licenze SupportEdge Premium e i codici prodotto di tali licenze variano in base alle opzioni selezionate nella progettazione FlexPod.



=== NetApp FAS

La tabella seguente elenca le opzioni di licenza di supporto NetApp per NetApp FAS.

|===
| Licenze NetApp Support | Codice del ricambio | Specifiche tecniche 


| SupportEdge Premium4 ore on-site; mesi: 36 | CS-O2-4HR | link:https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf["https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf"] 
|===


=== storage E-Series

La tabella seguente elenca le opzioni di licenza di supporto NetApp per storage E-Series.

|===
| Licenze NetApp Support | Codice del ricambio | Specifiche tecniche 


| Supporto hardware Premium 4 ore in loco; mesi: 36 | SVC-O2-4HR-E .3+| link:https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf["https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf"] 


| Supporto software | SW-SSP-O2-4HR-E 


| Installazione iniziale | SVC-INST-O2-4HR-E 
|===