---
sidebar: sidebar 
permalink: hybrid-cloud/cloud-fabricpool_introduction.html 
keywords: flexpod, fabricpool, inactive, data, tiering, amazon, aws, s3 
summary: 'Questo report tecnico analizza la funzionalità di tiering dei dati FabricPool di NetApp ONTAP nel contesto di un"architettura di infrastruttura convergente FlexPod di NetApp e Cisco.' 
---
= TR-4801: FlexPod con FabricPool - Tiering dei dati inattivi su Amazon AWS S3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Scott Kovacs, NetApp

[role="lead"]
I prezzi dello storage flash continuano a scendere, rendendolo disponibile per carichi di lavoro e applicazioni che non erano stati precedentemente considerati candidati per lo storage flash. Tuttavia, l'utilizzo più efficiente dell'investimento nello storage è ancora di fondamentale importanza per i responsabili IT. I reparti IT continuano a essere solleciti per offrire servizi dalle performance più elevate con un aumento minimo o nullo del budget. Per aiutare a soddisfare queste esigenze, NetApp FabricPool consente di sfruttare l'economia del cloud spostando i dati utilizzati di rado dal costoso storage flash on-premise a un Tier di storage più conveniente nel cloud pubblico. Lo spostamento nel cloud dei dati con accesso non frequente libera spazio prezioso di storage flash sui sistemi AFF o FAS per offrire maggiore capacità per i carichi di lavoro business-critical al Tier flash ad elevate performance.

Questo report tecnico analizza la funzionalità di tiering dei dati FabricPool di NetApp ONTAP nel contesto di un'architettura di infrastruttura convergente FlexPod di NetApp e Cisco. Per trarre il massimo vantaggio dai concetti discussi in questo report tecnico, è necessario conoscere l'architettura dell'infrastruttura convergente del data center FlexPod e il software di storage ONTAP. Sulla base della familiarità con FlexPod e ONTAP, discutiamo di FabricPool, del suo funzionamento e di come può essere utilizzato per ottenere un utilizzo più efficiente dello storage flash on-premise. Gran parte del contenuto di questo report viene trattato in maniera più dettagliata in https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598 FabricPool Best practice"^] E altra documentazione sui prodotti ONTAP. Il contenuto è stato condensato per un'infrastruttura FlexPod e non copre completamente tutti i casi di utilizzo di FabricPool. Tutte le funzionalità e i concetti esaminati sono disponibili in ONTAP 9.6.

Ulteriori informazioni su FlexPod sono disponibili in https://www.netapp.com/pdf.html?item=/media/12424-tr4036.pdf["Specifiche tecniche del data center TR-4036 FlexPod"^].
