---
sidebar: sidebar 
permalink: hybrid-cloud/fpd-ibn-cloud-design.html 
keywords: cisco, flexpod, ibm, data, center, cloud, private, storage 
summary: 'IBM Cloud Private (ICP) è una piattaforma on-premise per lo sviluppo e la gestione di applicazioni containerizzate per casi di utilizzo cloud-native e application-modernization' 
---
= Data center FlexPod con cloud privato IBM
:allow-uri-read: 


Sreenivasa Edula, Cisco Thanachit Wichianchai, IBM Jacky ben-Bassat, IBM Global Alliance, NetApp

[role="lead"]
IBM Cloud Private (ICP) è una piattaforma on-premise per lo sviluppo e la gestione di applicazioni containerizzate per casi di utilizzo cloud-native e application-modernization. Si tratta di un ambiente integrato basato su Kubernetes come orchestrazione di container e include un repository di immagini privato per container Docker, una console di gestione, un framework di monitoraggio, molte applicazioni open source e container IBM e molto altro ancora. Combinando ICP con FlexPod, l'infrastruttura convergente di Cisco e NetApp, è possibile semplificare l'implementazione e la gestione dell'infrastruttura. Puoi anche trarre vantaggio da una maggiore efficienza dello storage, una migliore protezione dei dati, una riduzione dei rischi e la flessibilità di scalare questo stack di infrastrutture Enterprise altamente disponibili per soddisfare nuovi requisiti di business e altre modifiche nel tempo.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_icp_ucsm32.html["Data center FlexPod con cloud privato IBM"^]
