---
sidebar: sidebar 
permalink: hybrid-cloud/gcp-ncvo-conclusion.html 
keywords: conclusion 
summary: 'In questa soluzione, il servizio dati cloud NetApp, Cloud Volumes ONTAP e l"infrastruttura del data center FlexPod sono stati utilizzati per creare una soluzione di DR con un cloud pubblico basato su Cisco Intersight Cloud Orchestrator. La soluzione FlexPod si è evoluta costantemente per consentire ai clienti di modernizzare le proprie applicazioni e i processi di business delivery. Con questa soluzione, è possibile creare un piano BCDR con il cloud pubblico come punto di accesso per un piano di disaster recovery transitorio o a tempo pieno, mantenendo al contempo bassi i costi della soluzione di disaster recovery.' 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


link:gcp-ncvo-solution-validation.html["Precedente: Convalida della soluzione."]

[role="lead"]
In questa soluzione, il servizio dati cloud NetApp, Cloud Volumes ONTAP e l'infrastruttura del data center FlexPod sono stati utilizzati per creare una soluzione di DR con un cloud pubblico basato su Cisco Intersight Cloud Orchestrator. La soluzione FlexPod si è evoluta costantemente per consentire ai clienti di modernizzare le proprie applicazioni e i processi di business delivery. Con questa soluzione, è possibile creare un piano BCDR con il cloud pubblico come punto di accesso per un piano di disaster recovery transitorio o a tempo pieno, mantenendo al contempo bassi i costi della soluzione di disaster recovery.

La replica dei dati tra FlexPod on-premise e NetApp Cloud Volumes ONTAP è stata gestita dalla comprovata tecnologia SnapMirror, ma è anche possibile selezionare altri strumenti di trasferimento e sincronizzazione dei dati NetApp come Cloud Sync per i requisiti di mobilità dei dati. Sicurezza dei dati in volo grazie alle tecnologie di crittografia integrate basate su TLS/AES.

Sia che si disponga di un piano di DR temporaneo per un'applicazione o di un piano di DR a tempo pieno per un'azienda, il portfolio di prodotti utilizzati in questa soluzione può soddisfare entrambi i requisiti su larga scala. Basato su Cisco Intersight Workflow Orchestrator, lo stesso può essere automatizzato con flussi di lavoro predefiniti che non solo eliminano la necessità di ricostruire i processi, ma accelerano anche l'implementazione di un piano BCDR.

La soluzione consente la gestione on-premise di FlexPod e la replica dei dati in un cloud ibrido in modo molto semplice e conveniente con l'automazione e l'orchestrazione fornite da Cisco Intersight Cloud Orchestrator.



[[where-to-find-additional-information]]
== Dove trovare ulteriori informazioni

Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:



[[github]]
=== GitHub

* Tutte le configurazioni terraform utilizzate
+
https://github.com/ucs-compute-solutions/cvo_snapmirror["https://github.com/ucs-compute-solutions/cvo_snapmirror"^]

* File JSON per l'importazione dei flussi di lavoro
+
https://github.com/ucs-compute-solutions/FlexPod_DR_Workflows["https://github.com/ucs-compute-solutions/FlexPod_DR_Workflows"^]





[[cisco-intersight]]
=== Cisco Intersight

* Centro assistenza Cisco Intersight
+
https://intersight.com/help/saas/home["https://intersight.com/help/saas/home"^]

* Documentazione di Cisco Intersight Cloud Orchestrator:
+
https://intersight.com/help/appliance/orchestration/configure["https://intersight.com/help/appliance/orchestration/configure"^]

* Cisco Intersight Service per documentazione HashiCorp Terraform
+
https://community.cisco.com/t5/data-center-and-cloud-knowledge-base/intersight-service-for-terraform/ta-p/4301093["https://community.cisco.com/t5/data-center-and-cloud-knowledge-base/intersight-service-for-terraform/ta-p/4301093"^]

* Scheda informativa su Cisco Intersight
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/intersight-ds.html["https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/intersight-ds.html"^]

* Scheda informativa di Cisco Intersight Cloud Orchestrator
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-cloud-orch-aag-cte-en.html["https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-cloud-orch-aag-cte-en.html"^]

* Scheda informativa di Cisco Intersight Service per HashiCorp Terraform
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-terraf-ser-aag-cte-en.html["https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-terraf-ser-aag-cte-en.html"^]





[[flexpod]]
=== FlexPod

* Pagina iniziale di FlexPod
+
https://www.flexpod.com["https://www.flexpod.com"^]

* Guide di progettazione e implementazione validate Cisco per FlexPod
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html["FlexPod Datacenter con Cisco UCS 4.2(1) in modalità gestita UCS, VMware vSphere 7.0 U2 e guida alla progettazione di NetApp ONTAP 9.9"^]

* Data center FlexPod con Cisco UCS serie X.
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html"^]





[[interoperability]]
=== Interoperabilità

* Tool di matrice di interoperabilità NetApp
+
http://mysupport.netapp.com/matrix["http://mysupport.netapp.com/matrix"^]

* Cisco UCS hardware and Software Interoperability Tool
+
http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html["http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html"^]

* Guida alla compatibilità VMware
+
http://www.vmware.com/resources/compatibility/search.php["http://www.vmware.com/resources/compatibility/search.php"^]





[[netapp-cloud-volumes-ontap-reference-documents]]
=== Documenti di riferimento NetApp Cloud Volumes ONTAP

* NetApp Console Documentazione:
+
https://docs.netapp.com/us-en/console-family/index.html["https://docs.netapp.com/us-en/console-family/index.html"^]

* Cloud Volumes ONTAP
+
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html[]

* Calcolatore TCO di Google Cloud con NetApp Cloud Volumes ONTAP
+
https://www.netapp.com/google-cloud/google-cloud-calculator/[]

* Dimensionamento e stima dei costi di Cloud Volumes ONTAP:
+
https://www.netapp.com/ontap-cloud/pricing/["https://www.netapp.com/ontap-cloud/pricing/"^]

* Valutazione del cloud e analisi dell'infrastruttura:
+
https://docs.netapp.com/us-en/data-infrastructure-insights/[]

* NetApp Soluzioni cloud ibrido:
+
https://www.netapp.com/hybrid-cloud/[]

* Documentazione API di Cloud Manager
+
https://docs.netapp.com/us-en/occm/reference_infrastructure_as_code.html["https://docs.netapp.com/us-en/occm/reference_infrastructure_as_code.html"^]





[[troubleshooting-issues]]
=== Risoluzione dei problemi

https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs["https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs"^]



[[terraform]]
=== Terraform

* Cloud terraformo
+
https://www.terraform.io/cloud["https://www.terraform.io/cloud"^]

* Documentazione terraform
+
https://www.terraform.io/docs/["https://www.terraform.io/docs/"^]

* Registro di NetApp Cloud Manager
+
https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/lates["https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/lates"^]





[[gcp]]
=== GCP

* Alta disponibilità ONTAP per GCP
+
https://bluexp.netapp.com/blog/gcp-cvo-blg-what-makes-cloud-volumes-ontap-high-availability-for-gcp-tick["https://bluexp.netapp.com/blog/gcp-cvo-blg-what-makes-cloud-volumes-ontap-high-availability-for-gcp-tick"^]

* Requisito GCP
+
https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f3d0368b-7165-4d43-a76e-ae01011853d6["https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f3d0368b-7165-4d43-a76e-ae01011853d6"^]


