---
sidebar: sidebar 
permalink: vdi/fpd-vmw-horiz-ontap.html 
keywords: flexpod, cisco, aff, vmware, horizon, vsphere, ucs, ontap, a300, design 
summary: 'Questo documento fornisce un"architettura di riferimento e una guida alla progettazione per un ambiente di elaborazione per l"utente finale con workload da 5000 postazioni a 6000 postazioni su FlexPod Datacenter con Cisco UCS e NetApp AFF A300 e il software per la gestione dei dati NetApp ONTAP.' 
---
= FlexPod Datacenter con VMware Horizon View 7.10, VMware vSphere 6.7 U2, Cisco UCS Manager 4.0 e NetApp ONTAP 9.6 per un massimo di 6700 postazioni
:allow-uri-read: 


Vadim Lebedev, Cisco Suresh Thoppay, NetApp

[role="lead"]
Questo documento fornisce un'architettura di riferimento e una guida alla progettazione per un ambiente di elaborazione per l'utente finale con workload da 5000 postazioni a 6000 postazioni su FlexPod Datacenter con Cisco UCS e NetApp AFF A300 e il software per la gestione dei dati NetApp ONTAP. La soluzione include sessioni RDS Windows Server 2019 basate su server VMware Horizon, desktop virtuali persistenti e cloni completi VMware Horizon Microsoft Windows 10 e desktop virtuali VMware Horizon non persistenti e con clonazione istantanea Microsoft Windows 10 su VMware vSphere 6.7 U2.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_ontap96_vmware710_67_u2_ucs_40_6700_seats.html["FlexPod Datacenter con VMware Horizon View 7.10, VMware vSphere 6.7 U2, Cisco UCS Manager 4.0 e NetApp ONTAP 9.6 per un massimo di 6700 postazioni"^]
