---
sidebar: sidebar 
permalink: vdi/fpd-citrix-vir.html 
keywords: flexpod, cisco, data, center, citrix, virtual, apps, vmware, vsphere 
summary: 'Questo documento fornisce l"architettura e la progettazione di un"infrastruttura di desktop virtuale per un massimo di 6000 utenti finali.' 
---
= Data center FlexPod con applicazioni virtuali Citrix e desktop 1912 LTSR e VMware vSphere 7 per un massimo di 6000 postazioni
:allow-uri-read: 


Jeff Nichols, Cisco Suresh Thoppay, NetApp Dre Jackson, NetApp

[role="lead"]
Questo documento fornisce l'architettura e la progettazione di un'infrastruttura di desktop virtuale per un massimo di 6000 utenti finali. La soluzione viene virtualizzata sui server blade Cisco UCS B200 M5 di quinta generazione, avviando VMware vSphere 7.01 Update 1 tramite FC SAN dall'array di storage AFF A400. I desktop virtuali sono alimentati con Citrix Provisioning Server 1912 LTSR e Citrix RDS/Citrix Virtual Apps & Desktops 1912 LTSR, con una combinazione di desktop condivisi in hosting RDS (6000), desktop virtuali Windows 10 in pool e/o non persistenti (5000), E desktop Windows 10 virtuali ospitati in maniera persistente con provisioning di Citrix Machine Creation Services (5000) per supportare la popolazione di utenti. Ove applicabile, il documento fornisce consigli sulle Best practice e linee guida per il dimensionamento per le implementazioni di questa soluzione da parte dei clienti.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/cisco_ucs_ctx1912esxi7u1_flexpodV2.html["Data center FlexPod con applicazioni virtuali Citrix  desktop 1912 LTSR e VMware vSphere 7 per un massimo di 6000 postazioni"^]
