---
sidebar: sidebar 
permalink: flexpod-dc/fpd-mcc-vsphere-design.html 
keywords: flexpod, cisco, data, center, aci, mcc, ip, vmware, vsphere, aci 
summary: 'Questo documento descrive l"integrazione del multi-pod Cisco ACI e della soluzione NetApp MetroCluster IP nel data center FlexPod per fornire una soluzione multi-data center altamente disponibile.' 
---
= FlexPod Datacenter con Cisco ACI Multi-Pod, NetApp MetroCluster IP e VMware vSphere 6.7 - progettazione
:allow-uri-read: 


Haseeb Niazi, Cisco Arvind Ramakrishnan, NetApp

[role="lead"]
Questo documento descrive l'integrazione del multi-pod Cisco ACI e della soluzione NetApp MetroCluster IP nel data center FlexPod per fornire una soluzione multi-data center altamente disponibile. L'architettura multi-data center offre la possibilità di bilanciare i carichi di lavoro tra due data center utilizzando la mobilità dei carichi di lavoro senza interruzioni, consentendo così la migrazione dei servizi tra siti senza la necessità di sostenere un'interruzione del servizio.

La soluzione FlexPod con multi-pod ACI e NetApp MetroCluster IP offre i seguenti vantaggi:

* Mobilità perfetta dei carichi di lavoro nei data center
* Policy coerenti in tutti i siti
* Estensione Layer-2 in data center geograficamente distribuiti
* Migliore prevenzione dei downtime durante la manutenzione
* Prevenzione e ripristino di disastri


link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi67_n9k_aci_metrocluster_design.html["FlexPod Datacenter con Cisco ACI Multi-Pod, NetApp MetroCluster IP e VMware vSphere 6.7 - progettazione"^]
