---
sidebar: sidebar 
permalink: flexpod-dc/fpd-mcc-vsphere-deploy.html 
keywords: flexpod, cisco, data, center, aci, multi-pod, mcc, ip, vmware, vsphere, deployment 
summary: Cisco e NetApp hanno collaborato per offrire una serie di soluzioni FlexPod che consentono piattaforme strategiche per data center. 
---
= Data center FlexPod con multi-pod Cisco ACI con NetApp MetroCluster IP e VMware vSphere 6.7 - implementazione
:allow-uri-read: 


Haseeb Niazi, Cisco Ramesh Issac, Cisco Arvind Ramakrishnan, NetApp

[role="lead"]
Cisco e NetApp hanno collaborato per offrire una serie di soluzioni FlexPod che consentono piattaforme strategiche per data center. La soluzione FlexPod offre un'architettura integrata che incorpora le Best practice di progettazione per il calcolo, lo storage e il networking, riducendo al minimo i rischi PER L'IT convalidando l'architettura integrata per garantire la compatibilità tra i vari componenti. La soluzione affronta anche i punti critici DELL'IT fornendo una guida documentata alla progettazione, una guida all'implementazione e un supporto che possono essere utilizzati in varie fasi (pianificazione, progettazione e implementazione) di un'implementazione.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi67_n9k_aci_metrocluster.html["Data center FlexPod con multi-pod Cisco ACI con NetApp MetroCluster IP e VMware vSphere 6.7 - implementazione"^]
