---
sidebar: sidebar 
permalink: flexpod-dc/vmware-vsphere-70-ontap-97.html 
keywords:  
summary: 'Cisco Validated Designs (CVD) include sistemi e soluzioni progettati, testati e documentati per facilitare e migliorare le implementazioni dei clienti.' 
---
= Data center FlexPod con VMware vSphere 7.0 e NetApp ONTAP 9.7
:allow-uri-read: 


John George, Cisco Sree Lakshmi Lanka, NetApp

[role="lead"]
Cisco Validated Designs (CVD) include sistemi e soluzioni progettati, testati e documentati per facilitare e migliorare le implementazioni dei clienti. Questi design incorporano un'ampia gamma di tecnologie e prodotti in un portfolio di soluzioni sviluppate per soddisfare le esigenze di business dei clienti. Cisco e NetApp hanno collaborato per offrire FlexPod®, che funge da base per una varietà di carichi di lavoro e consente progettazioni architetturali efficienti basate sui requisiti del cliente. Una soluzione FlexPod è un approccio validato per l'implementazione delle tecnologie Cisco e NetApp come infrastruttura cloud condivisa.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/fp_vmware_vsphere_7_0_ontap_9_7.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/fp_vmware_vsphere_7_0_ontap_9_7.html"^]
