---
sidebar: sidebar 
permalink: security/flexpod-fips-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Riconoscimenti, cronologia delle versioni e dove trovare ulteriori informazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-fips-conclusion.html["Precedente: Conclusione."]

[role="lead"]
Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e siti Web:

* Guida alla configurazione della sicurezza NX-OS della famiglia Cisco MDS 9000
+
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/sw/8_x/config/security/cisco_mds9000_security_config_guide_8x/configuring_fips.html#task_1188151[]

* Cisco Nexus 9000 Series NX-OS Security Configuration Guide, Release 9.3(x)
+
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/93x/security/configuration/guide/b-cisco-nexus-9000-nx-os-security-configuration-guide-93x/m-configuring-fips.html[]

* NetApp e la pubblicazione FIPS (Federal Information Processing Standard) 140-2
+
https://www.netapp.com/company/trust-center/compliance/fips-140-2/[]

* FIPS 140-2
+
https://fieldportal.netapp.com/s/article/tr4781-fips-1402-1694000809616[]

* Guida al rafforzamento di NetApp ONTAP 9
+
https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf[]

* NetApp Encryption Power Guide
+
https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.pow-nve%2Fhome.html[]

* Scheda informativa su NVE e NAE
+
https://www.netapp.com/pdf.html?item=/media/17070-ds-3899.pdf[]

* Scheda informativa NSE
+
https://www.netapp.com/pdf.html?item=/media/7563-ds-3213-en.pdf[]

* Centro documentazione di ONTAP 9
+
http://docs.netapp.com[]

* NetApp e la pubblicazione FIPS (Federal Information Processing Standard) 140-2
+
https://www.netapp.com/company/trust-center/compliance/fips-140-2/[]

* Conformità Cisco e FIPS 140-2
+
https://www.cisco.com/c/en/us/solutions/industries/government/global-government-certifications/fips-140.html[]

* NetApp Cryptographic Security Module
+
https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2648.pdf[]

* Procedure di cybersecuryper le organizzazioni sanitarie di medie e grandi dimensioni
+
https://hhscyber.hhs.gov/Documents/HICP/tech-vol2-508.pdf[]

* Programma di convalida dei moduli crittografici (CMVP). Database NIST CMVP per i moduli crittografici convalidati, incluse le offerte Cisco.
+
https://csrc.nist.gov/projects/cryptographic-module-validation-program[]

* NetApp Storage Encryption, NVMe Self-Encrypting Drive, NetApp Volume Encryption e NetApp aggregate Encryption
+
https://www.netapp.com/pdf.html?item=/media/17073-ds-3898.pdf[]

* NetApp Volume Encryption e NetApp aggregate Encryption
+
https://www.netapp.com/pdf.html?item=/media/17070-ds-3899.pdf[]

* Crittografia dello storage NetApp
+
https://www.netapp.com/pdf.html?item=/media/7563-ds-3213-en.pdf[]

* FlexPod per sistemi di cartella clinica elettronica
+
https://www.netapp.com/pdf.html?item=/media/22199-tr-4881.pdf[]

* Data Now: Miglioramento delle performance negli ambienti Epic EHR con la tecnologia flash connessa al cloud
+
https://www.netapp.com/media/10809-cloud-connected-flash-wp.pdf[]

* Data center FlexPod per l'infrastruttura EHR Epic
+
https://www.netapp.com/pdf.html?item=/media/17061-ds-3683.pdf[]

* Guida all'implementazione di FlexPod Datacenter per Epic EHR
+
https://www.netapp.com/media/10658-tr-4693.pdf[]

* FlexPod per imaging medicale
+
https://www.netapp.com/media/19793-tr-4865.pdf[]

* Ai nel settore sanitario
+
https://www.netapp.com/pdf.html?item=/media/7393-na-369pdf.pdf[]

* FlexPod per il settore sanitario semplifica la tua trasformazione
+
https://flexpod.com/solutions/verticals/healthcare/[]

* FlexPod di Cisco e NetApp
+
https://flexpod.com/[]





[[acknowledgements]]
== Ringraziamenti

* Abhinav Singh, Technical Marketing Engineer, NetApp
* Brian o'Mahony, Solution Architect Healthcare (Epic), NetApp
* Brian Pruitt, Pursuit Business Development Manager, NetApp
* Arvind Ramakrishnan, Senior Solutions Architect, NetApp
* Michael Hommer, FlexPod Global Field CTO, NetApp




[[version-history]]
== Cronologia delle versioni

|===
| Versione | Data | Cronologia delle versioni del documento 


| Versione 1.0 | Aprile 2021 | Release iniziale 
|===