---
sidebar: sidebar 
permalink: ent-db/fpd-sap-sql-deploy.html 
keywords: flexpod, cisco, sap, sql, servers, data, bases 
summary: FlexPod è una soluzione di data center pre-validata e progettata per soddisfare le esigenze in rapida evoluzione dei reparti IT. 
---
= Implementare server di applicazioni SAP su FlexPod con SQL
:allow-uri-read: 


[role="lead"]
FlexPod è una soluzione di data center pre-validata e progettata per soddisfare le esigenze in rapida evoluzione dei reparti IT. Cisco e NetApp hanno collaborato per offrire FlexPod, che utilizza componenti di calcolo, networking e storage Best-in-class come base per una varietà di carichi di lavoro aziendali, tra cui database, pianificazione delle risorse aziendali (ERP), gestione delle relazioni con i clienti (CRM) e applicazioni web. Il consolidamento delle applicazioni IT, in particolare dei database, ha suscitato un notevole interesse negli ultimi anni. La piattaforma di database più diffusa e implementata negli ultimi anni è Microsoft SQL Server. I database di SQL Server sono spesso soggetti a una crescita incontrollata dei database, che comporta sfide IT come server sottoutilizzati, licenze non corrette, problemi di sicurezza, problemi di gestione e costi operativi enormi. Pertanto, i database di SQL Server sono buoni candidati per il consolidamento su una piattaforma più solida, flessibile e resiliente. In questo documento viene illustrata un'architettura di riferimento di FlexPod per la distribuzione e il consolidamento dei database SQL Server.

link:https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/sap-appservers-flexpod-with-sql.pdf["Implementare server di applicazioni SAP su FlexPod con SQL"^]
