---
sidebar: sidebar 
permalink: ent-db/fpd-oracle-rac-db.html 
keywords: flexpod, datacenter, oracle, rac, cisco, ucs, aff, mds, deploy 
summary: I Cisco Validated Design includono sistemi e soluzioni progettati, testati e documentati per facilitare e migliorare le implementazioni dei clienti. 
---
= Data center FlexPod con database RAC Oracle su Cisco UCS e NetApp AFF A-Series
:allow-uri-read: 


Tushar Patel, Cisco Hardikkumar Vyas, Cisco

[role="lead"]
I Cisco Validated Design includono sistemi e soluzioni progettati, testati e documentati per facilitare e migliorare le implementazioni dei clienti. Questi design incorporano un'ampia gamma di tecnologie e prodotti in un portfolio di soluzioni sviluppate per soddisfare le esigenze di business dei clienti. Cisco e NetApp hanno collaborato per offrire FlexPod, che funge da base per una varietà di carichi di lavoro e consente progettazioni architetturali efficienti basate sui requisiti del cliente. Una soluzione FlexPod è un approccio validato per l'implementazione delle tecnologie Cisco e NetApp come infrastruttura cloud condivisa.

Il sistema FlexPod Datacenter con NetApp All Flash AFF è una piattaforma di infrastruttura convergente che combina le migliori tecnologie di Cisco e NetApp in una potente piattaforma convergente per le applicazioni aziendali. Cisco e NetApp collaborano a stretto contatto con Oracle per supportare i database transazionali e sensibili ai tempi di risposta più esigenti richiesti dalle aziende di oggi.

Questo progetto validato Cisco (CVD) descrive l'architettura di riferimento di FlexPod Datacenter che utilizza Cisco UCS e NetApp All Flash AFF per l'implementazione di un ambiente di database Oracle RAC ad alta disponibilità. Questo documento mostra la configurazione hardware e software dei componenti coinvolti e i risultati di vari test. Inoltre, il presente documento offre una guida all'implementazione e alle Best practice per l'utilizzo di server di calcolo Cisco UCS, switch di interconnessione Cisco Fabric, switch Cisco MDS, switch Cisco Nexus, storage NetApp AFF e database Oracle RAC.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orc12cr2_affaseries.html["Data center FlexPod con database RAC Oracle su Cisco UCS e NetApp AFF A-Series"^]
