---
sidebar: sidebar 
permalink: ent-db/fpd-microsoft-sql-vsphere.html 
keywords: flexpod, microsoft, cisco, sql, vmware, vsphere, ucs 
summary: 'Questo documento descrive un"architettura di riferimento di FlexPod che utilizza i prodotti hardware e software più recenti e fornisce consigli sull"implementazione per l"hosting di database Microsoft SQL Server 2019 in ambienti virtualizzati VMware ESXi.' 
---
= Data center FlexPod per Microsoft SQL Server 2019 e VMware vSphere 6.7
:allow-uri-read: 


Gopu Narasimha Reddy, Cisco Sanjeev Naldurgkar, Cisco Atul Balodia, NetApp

[role="lead"]
Questo documento descrive un'architettura di riferimento di FlexPod che utilizza i prodotti hardware e software più recenti e fornisce consigli sull'implementazione per l'hosting di database Microsoft SQL Server 2019 in ambienti virtualizzati VMware ESXi. Questa soluzione utilizza anche Cisco workload Optimization Manager (CWOM), che fornisce consigli automatizzati per un utilizzo ottimale ed efficiente delle risorse per entrambi i carichi di lavoro SQL.

La soluzione si basa su Cisco Unified Computing System (Cisco UCS) utilizzando la versione software unificata 4.1.1c per supportare le piattaforme hardware Cisco UCS, inclusi i server blade Cisco UCS serie B, le interconnessioni fabric Cisco UCS 6400, gli switch Cisco Nexus serie 9000 e gli array di storage NetApp serie AFF.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/mssql2019_flexpod.html["Data center FlexPod per Microsoft SQL Server 2019 e VMware vSphere 6.7"^]
