---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_requirements.html 
keywords: netapp, ontap, cisco, intersight, hardware, software, licensing, requirements 
summary: 'Verifica di soddisfare i requisiti hardware, software e di licenza per l"integrazione dello storage NetApp ONTAP con Cisco Intersight.' 
---
= Requisiti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Verifica di soddisfare i requisiti di hardware, software e licenze per l'integrazione dello storage NetApp ONTAP con Cisco Intersight.



== Requisiti hardware e software

Questi sono i componenti hardware e software minimi necessari per implementare la soluzione. I componenti utilizzati in una particolare implementazione della soluzione possono variare in base ai requisiti del cliente.

|===
| Componente | Dettagli dei requisiti 


| NetApp ONTAP | ONTAP 9.7P1 e versioni successive 


| NetApp Active IQ Unified Manager | È richiesta l'ultima versione di NetApp Active IQ Unified Manager (attualmente 9.14RC1) 


| Storage array NetApp | Tutti gli storage array ONTAP ASA, AFF e FAS supportati per ONTAP 9.7P1 e versioni successive 


| Hypervisor per la virtualizzazione | VSphere 7,0 e versioni successive 
|===

NOTE: Fare riferimento a. https://intersight.com/help/saas/supported_systems["Sistemi supportati da Cisco Intersight"^] Per i requisiti minimi di Cisco UCS Compute Components e della versione di UCSM.



== Requisiti di licenza di Cisco Intersight

Cisco Intersight offre servizi come Servizio dell'infrastruttura e Servizio orchestratore cloud per gestire, automatizzare e ottimizzare lo storage fisico (storage NetApp). Puoi utilizzare questi servizi per gestire il server Cisco UCS e il sistema Cisco HyperFlex. Il servizio Infrastructure Service e Cloud Orchestrator utilizzano un modello di licenza basato su abbonamento con diversi Tier. Puoi scegliere il Tier di volume Cisco UCS Server richiesto per il termine di iscrizione selezionato.

.Modello di licenza
Il modello di licenza di Cisco Intersight Infrastructure Services è stato semplificato e ora offre i seguenti due livelli:

* *Cisco Intersight Infrastructure Services Essentials* - il livello di licenza Essentials offre la gestione dei server, tra cui funzionalità di monitoraggio dello stato globale, inventario, supporto proattivo tramite l'integrazione Cisco TAC, autenticazione a più fattori e accesso a SDK e API.
* *Cisco Intersight Infrastructure Services Advantage* - il livello di licenza Advantage offre una gestione avanzata dei server con visibilità estesa, integrazione dell'ecosistema, automazione di hardware e software Cisco e di terze parti, oltre a fornire soluzioni multi-dominio.


Per ulteriori informazioni sulle funzionalità coperte da diversi livelli di licenza, visitare il sito Web all'indirizzo https://intersight.com/help/saas/getting_started/licensing_requirements/lic_infra#licensing_model["Licenza dei servizi di infrastruttura"^].
